import { groundA1TunnelCVisibleSupportHardwareV3 as groundV5 } from "./a1TunnelCVisibleSupportGroundingV5.js";

const MAX_FINAL_CLEARANCE_METERS = 0.015;
const MAX_EXTENSION_METERS = 2.2;
const MAX_TOP_MOUNT_DRIFT_METERS = 0.015;
const LOWER_RIGID_FRACTION = 0.22;
const UPPER_RIGID_FRACTION = 0.80;
const VERTEX_KEY_SCALE = 10000;
const PHOTO_GROUND_NAMES = Object.freeze(["PHX_KPHX_SourceAuthoredPhotoGround_Tiled", "PHX_KPHX_SourceAuthoredPhotoGround"]);
function vk(p,i){return `${Math.round(p.getX(i)*VERTEX_KEY_SCALE)},${Math.round(p.getY(i)*VERTEX_KEY_SCALE)},${Math.round(p.getZ(i)*VERTEX_KEY_SCALE)}`;}
function components(p){const n=p.count/3,par=new Int32Array(n);for(let i=0;i<n;i++)par[i]=i;const f=(v)=>{let r=v;while(par[r]!==r)r=par[r];while(par[v]!==v){const q=par[v];par[v]=r;v=q;}return r;};const u=(a,b)=>{a=f(a);b=f(b);if(a!==b)par[b]=a;};const seen=new Map();for(let t=0;t<n;t++)for(let c=0;c<3;c++){const k=vk(p,t*3+c),x=seen.get(k);if(x===undefined)seen.set(k,t);else u(t,x);}const out=new Map();for(let t=0;t<n;t++){const r=f(t);if(!out.has(r))out.set(r,[]);out.get(r).push(t);}return [...out.values()];}
function sceneRoot(o){let r=o;while(r?.parent)r=r.parent;return r;}
function resolveGround(r){for(const n of PHOTO_GROUND_NAMES){const g=r?.getObjectByName?.(n);if(g)return g;}throw new Error("A1 V8 cannot resolve KPHX pavement");}
function groundY(THREE,g,x,z,high){const ray=new THREE.Raycaster(new THREE.Vector3(x,high+40,z),new THREE.Vector3(0,-1,0));ray.far=200;const h=ray.intersectObject(g,true)[0];if(!h?.point)throw new Error(`A1 V8 no pavement under ${x},${z}`);return h.point.y;}
function center(THREE,o){return o?new THREE.Box3().setFromObject(o).getCenter(new THREE.Vector3()):null;}
function measure(THREE,mesh,p,tris,rot,cab){const b=new THREE.Box3(),l=new THREE.Vector3(),w=new THREE.Vector3();for(const t of tris)for(let c=0;c<3;c++){l.fromBufferAttribute(p,t*3+c);b.expandByPoint(w.copy(l).applyMatrix4(mesh.matrixWorld));}const s=b.getSize(new THREE.Vector3()),ct=b.getCenter(new THREE.Vector3()),hs=Math.max(s.x,s.z);const br=cab.clone().sub(rot).setY(0),a=ct.clone().sub(rot).setY(0).dot(br)/br.lengthSq(),q=rot.clone().addScaledVector(br,a),lat=Math.hypot(ct.x-q.x,ct.z-q.z);return{tris,box:b,size:s,center:ct,horizontalSpan:hs,aspect:s.y/Math.max(hs,.01),along:a,lateral:lat};}
function isTarget(e){if(!(e.along>=0.75&&e.along<=0.86&&e.lateral>=1.5&&e.lateral<=4.2))return false;const large=e.tris.length>=50&&e.tris.length<=90&&e.size.y>=0.60&&e.size.y<=0.85&&e.horizontalSpan>=0.70&&e.horizontalSpan<=0.90;const narrow=e.tris.length>=4&&e.tris.length<=8&&e.size.y>=0.085&&e.size.y<=0.125&&e.horizontalSpan>=0.025&&e.horizontalSpan<=0.13&&e.aspect>=0.8;return large||narrow;}
function indices(tris){const s=new Set();for(const t of tris){s.add(t*3);s.add(t*3+1);s.add(t*3+2);}return [...s];}
function telescope(THREE,mesh,p,e,ramp){const min=e.box.min.y,max=e.box.max.y,h=max-min,ext=min-ramp;if(!(ext>MAX_FINAL_CLEARANCE_METERS&&ext<=MAX_EXTENSION_METERS))throw new Error(`A1 V8 target extension out of range ${ext}`);const inv=mesh.matrixWorld.clone().invert(),l=new THREE.Vector3(),w=new THREE.Vector3();for(const i of indices(e.tris)){l.fromBufferAttribute(p,i);w.copy(l).applyMatrix4(mesh.matrixWorld);const f=Math.max(0,Math.min(1,(w.y-min)/h));let d=0;if(f<=LOWER_RIGID_FRACTION)d=ext;else if(f<UPPER_RIGID_FRACTION)d=ext*(1-(f-LOWER_RIGID_FRACTION)/(UPPER_RIGID_FRACTION-LOWER_RIGID_FRACTION));w.y-=d;l.copy(w).applyMatrix4(inv);p.setXYZ(i,l.x,l.y,l.z);}return{top:max,ext};}
export function groundA1TunnelCVisibleSupportHardwareV3(THREE,model){const base=groundV5(THREE,model),mesh=model?.getObjectByName?.("Tunnel_B_Jetway_0");if(!mesh?.isMesh)throw new Error("A1 V8 cannot resolve Tunnel_B_Jetway_0");const root=sceneRoot(model),g=resolveGround(root);root.updateWorldMatrix?.(true,true);model.updateWorldMatrix(true,true);mesh.updateWorldMatrix(true,false);const rot=center(THREE,model.getObjectByName("Rotunda")),cab=center(THREE,model.getObjectByName("Cab"));const geometry=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone(),p=geometry.getAttribute("position");const targets=[];for(const tris of components(p)){const e=measure(THREE,mesh,p,tris,rot,cab);if(!isTarget(e))continue;e.ramp=groundY(THREE,g,e.center.x,e.center.z,e.box.max.y);e.clearance=e.box.min.y-e.ramp;if(e.clearance>MAX_FINAL_CLEARANCE_METERS&&e.clearance<=MAX_EXTENSION_METERS)targets.push(e);}if(targets.length!==6)throw new Error(`A1 V8 expected exact six Tunnel-B visible support islands from diagnostic, found ${targets.length}: ${JSON.stringify(targets.map(e=>({tris:e.tris.length,clearance:e.clearance,along:e.along,lateral:e.lateral,size:e.size.toArray()})))}`);mesh.geometry=geometry;const corrected=targets.map(e=>({e,...telescope(THREE,mesh,p,e,e.ramp)}));p.needsUpdate=true;geometry.computeBoundingBox();geometry.computeBoundingSphere();mesh.updateMatrixWorld(true);model.updateWorldMatrix(true,true);let maxClear=base.maximumFinalClearanceMeters,maxDrift=base.maximumTopMountDriftMeters;for(const c of corrected){const m=measure(THREE,mesh,p,c.e.tris,rot,cab),r=groundY(THREE,g,m.center.x,m.center.z,m.box.max.y),cl=m.box.min.y-r,dr=Math.abs(m.box.max.y-c.top);maxClear=Math.max(maxClear,Math.abs(cl));maxDrift=Math.max(maxDrift,dr);if(cl>MAX_FINAL_CLEARANCE_METERS)throw new Error(`A1 V8 Tunnel-B support still suspended ${cl}`);}if(maxClear>MAX_FINAL_CLEARANCE_METERS)throw new Error(`A1 V8 max clearance ${maxClear}`);if(maxDrift>MAX_TOP_MOUNT_DRIFT_METERS)throw new Error(`A1 V8 top drift ${maxDrift}`);const extraCount=corrected.length,extraTriangles=corrected.reduce((s,c)=>s+c.e.tris.length,0),secondary=base.secondaryMeshGroundedCount+extraCount,correctedCount=base.groundedComponentCount+secondary;return Object.freeze({...base,secondaryMeshGroundedCount:secondary,secondaryMeshGroundedTriangleCount:base.secondaryMeshGroundedTriangleCount+extraTriangles,spatialRodClusterCount:base.spatialRodClusterCount+extraCount,spatialRodTriangleCount:base.spatialRodTriangleCount+extraTriangles,spatialRodVertexCount:base.spatialRodVertexCount+extraTriangles*3,correctedSupportSetCount:correctedCount,visibleLoadLegCount:correctedCount,remainingSuspendedSupportCount:0,maximumFinalClearanceMeters:maxClear,maximumTopMountDriftMeters:maxDrift,maximumExtensionMeters:Math.max(base.maximumExtensionMeters,...corrected.map(c=>c.ext)),rampReferenceComponentCount:correctedCount,v8TunnelBVisibleSupportCount:extraCount,v8TunnelBVisibleSupportTriangleCount:extraTriangles});}
export { A1_TUNNEL_C_VISIBLE_SUPPORT_GROUNDING_V3_AUTHORITY, A1_TUNNEL_C_VISIBLE_SUPPORT_SECONDARY_MESH_AUTHORITY } from "./a1TunnelCVisibleSupportGroundingV5.js";
