import { groundA1TunnelCVisibleSupportHardwareV3 as groundV5 } from "./a1TunnelCVisibleSupportGroundingV5.js";

const VERTEX_KEY_SCALE = 10000;
const PHOTO_GROUND_NAMES = Object.freeze(["PHX_KPHX_SourceAuthoredPhotoGround_Tiled", "PHX_KPHX_SourceAuthoredPhotoGround"]);
function key(p,i){return `${Math.round(p.getX(i)*VERTEX_KEY_SCALE)},${Math.round(p.getY(i)*VERTEX_KEY_SCALE)},${Math.round(p.getZ(i)*VERTEX_KEY_SCALE)}`;}
function comps(p){if(!p||p.count%3!==0)return[];const n=p.count/3,par=new Int32Array(n);for(let i=0;i<n;i++)par[i]=i;const f=(v)=>{let r=v;while(par[r]!==r)r=par[r];while(par[v]!==v){const q=par[v];par[v]=r;v=q;}return r;};const u=(a,b)=>{a=f(a);b=f(b);if(a!==b)par[b]=a;};const m=new Map();for(let t=0;t<n;t++)for(let c=0;c<3;c++){const k=key(p,t*3+c),x=m.get(k);if(x===undefined)m.set(k,t);else u(t,x);}const out=new Map();for(let t=0;t<n;t++){const r=f(t);if(!out.has(r))out.set(r,[]);out.get(r).push(t);}return [...out.values()];}
function root(o){let r=o;while(r?.parent)r=r.parent;return r;}
function ground(rootObj){for(const n of PHOTO_GROUND_NAMES){const g=rootObj?.getObjectByName?.(n);if(g)return g;}throw new Error("A1 V7 diagnostic cannot find KPHX pavement");}
function gy(THREE,g,x,z,y){const ray=new THREE.Raycaster(new THREE.Vector3(x,y+40,z),new THREE.Vector3(0,-1,0));ray.far=200;const h=ray.intersectObject(g,true)[0];return h?.point?.y;}
function center(THREE,o){return o?new THREE.Box3().setFromObject(o).getCenter(new THREE.Vector3()):null;}
function measure(THREE,mesh,p,tris,rot,cab){const b=new THREE.Box3(),l=new THREE.Vector3(),w=new THREE.Vector3();for(const t of tris)for(let c=0;c<3;c++){l.fromBufferAttribute(p,t*3+c);b.expandByPoint(w.copy(l).applyMatrix4(mesh.matrixWorld));}const s=b.getSize(new THREE.Vector3()),ct=b.getCenter(new THREE.Vector3()),hs=Math.max(s.x,s.z);let a=NaN,lat=NaN;if(rot&&cab){const br=cab.clone().sub(rot).setY(0);if(br.lengthSq()>1){a=ct.clone().sub(rot).setY(0).dot(br)/br.lengthSq();const q=rot.clone().addScaledVector(br,a);lat=Math.hypot(ct.x-q.x,ct.z-q.z);}}return{mesh:mesh.name||"<unnamed>",tris:tris.length,min:[b.min.x,b.min.y,b.min.z],max:[b.max.x,b.max.y,b.max.z],size:[s.x,s.y,s.z],center:[ct.x,ct.y,ct.z],horizontalSpan:hs,verticalAspect:s.y/Math.max(hs,.01),along:a,lateral:lat};}
export function groundA1TunnelCVisibleSupportHardwareV3(THREE,model){const base=groundV5(THREE,model);const scene=root(model),g=ground(scene);scene.updateWorldMatrix?.(true,true);model.updateWorldMatrix(true,true);const rot=center(THREE,model.getObjectByName("Rotunda")),cab=center(THREE,model.getObjectByName("Cab"));const candidates=[];model.traverse((mesh)=>{if(!mesh?.isMesh||mesh.name==="Tunnel_C_Jetway_0")return;mesh.updateWorldMatrix(true,false);const p=mesh.geometry?.getAttribute?.("position");if(!p||p.count%3!==0)return;for(const tris of comps(p)){const e=measure(THREE,mesh,p,tris,rot,cab);if(!(Number.isFinite(e.along)&&e.along>=.15&&e.along<=1.25&&Number.isFinite(e.lateral)&&e.lateral<=8&&e.tris>=2&&e.tris<=3500&&e.size[1]>=.08&&e.size[1]<=5.5&&e.horizontalSpan>=.01&&e.horizontalSpan<=2.8&&e.verticalAspect>=.45))continue;const y=gy(THREE,g,e.center[0],e.center[2],e.max[1]);if(!Number.isFinite(y))continue;e.rampY=y;e.clearance=e.min[1]-y;if(e.clearance>.015&&e.clearance<=4.5)candidates.push(e);}});candidates.sort((a,b)=>b.clearance-a.clearance||b.verticalAspect-a.verticalAspect);if(candidates.length){const concise=candidates.slice(0,40).map(e=>({mesh:e.mesh,tris:e.tris,clearance:+e.clearance.toFixed(4),along:+e.along.toFixed(3),lateral:+e.lateral.toFixed(3),size:e.size.map(v=>+v.toFixed(3)),min:e.min.map(v=>+v.toFixed(3)),max:e.max.map(v=>+v.toFixed(3)),center:e.center.map(v=>+v.toFixed(3)),aspect:+e.verticalAspect.toFixed(2)}));throw new Error(`A1 V7 SECONDARY SUSPENDED COMPONENT DIAGNOSTIC ${JSON.stringify(concise)}`);}return base;}
export { A1_TUNNEL_C_VISIBLE_SUPPORT_GROUNDING_V3_AUTHORITY, A1_TUNNEL_C_VISIBLE_SUPPORT_SECONDARY_MESH_AUTHORITY } from "./a1TunnelCVisibleSupportGroundingV5.js";
