import { groundA1TunnelCVisibleSupportHardwareV3 as groundV14 } from "./a1TunnelCVisibleSupportGroundingV14.js";

const GROUND_NAMES = ["PHX_KPHX_SourceAuthoredPhotoGround_Tiled", "PHX_KPHX_SourceAuthoredPhotoGround"];
const TARGETS = [
  { centerX: -11.22, centerZ: 10.14, half: 0.06, expectedTriangles: 63 },
  { centerX: -13.02, centerZ: 10.38, half: 0.06, expectedTriangles: 45 },
];
const MAX_CLEAR = 0.015;
const MAX_TOP_DRIFT = 0.015;
const MAX_EXTENSION = 1.55;
function rootOf(o){let r=o;while(r?.parent)r=r.parent;return r;}
function groundOf(root){for(const n of GROUND_NAMES){const g=root?.getObjectByName?.(n);if(g)return g;}throw new Error("A1 V17 no rendered pavement");}
function groundY(THREE,g,x,z,y){const ray=new THREE.Raycaster(new THREE.Vector3(x,y+40,z),new THREE.Vector3(0,-1,0));ray.far=200;const hit=ray.intersectObject(g,true)[0];if(!hit?.point)throw new Error("A1 V17 pavement ray miss");return hit.point.y;}
function select(THREE,mesh,pos,target){const ids=[],l=new THREE.Vector3(),w=new THREE.Vector3();for(let t=0;t<pos.count/3;t++){let sx=0,sy=0,sz=0;for(let c=0;c<3;c++){l.fromBufferAttribute(pos,t*3+c);w.copy(l).applyMatrix4(mesh.matrixWorld);sx+=w.x;sy+=w.y;sz+=w.z;}const x=sx/3,z=sz/3;if(Math.abs(x-target.centerX)<=target.half&&Math.abs(z-target.centerZ)<=target.half)ids.push(t);}return ids;}
function boxFor(THREE,mesh,pos,triangles){const b=new THREE.Box3(),l=new THREE.Vector3(),w=new THREE.Vector3();for(const t of triangles)for(let c=0;c<3;c++){l.fromBufferAttribute(pos,t*3+c);b.expandByPoint(w.copy(l).applyMatrix4(mesh.matrixWorld));}return b;}
function stretch(THREE,mesh,pos,triangles,ramp){const before=boxFor(THREE,mesh,pos,triangles),min=before.min.y,max=before.max.y,h=max-min,ext=min-ramp;if(!(h>0.2)||ext<=MAX_CLEAR||ext>MAX_EXTENSION)throw new Error(`A1 V17 invalid support span/extension h=${h} ext=${ext}`);const inv=mesh.matrixWorld.clone().invert(),l=new THREE.Vector3(),w=new THREE.Vector3();for(const t of triangles)for(let c=0;c<3;c++){const i=t*3+c;l.fromBufferAttribute(pos,i);w.copy(l).applyMatrix4(mesh.matrixWorld);const f=Math.max(0,Math.min(1,(w.y-min)/h));w.y=ramp+f*(max-ramp);l.copy(w).applyMatrix4(inv);pos.setXYZ(i,l.x,l.y,l.z);}return {beforeTop:max,extension:ext};}
export function groundA1TunnelCVisibleSupportHardwareV3(THREE,model){const base=groundV14(THREE,model),root=rootOf(model),ground=groundOf(root),mesh=model?.getObjectByName?.("Tunnel_B_Jetway_0");if(!mesh?.isMesh)throw new Error("A1 V17 no Tunnel_B_Jetway_0");root.updateWorldMatrix?.(true,true);model.updateWorldMatrix(true,true);mesh.updateWorldMatrix(true,false);mesh.geometry=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();const pos=mesh.geometry.getAttribute("position"),done=[];for(const target of TARGETS){const tris=select(THREE,mesh,pos,target);if(tris.length!==target.expectedTriangles)throw new Error(`A1 V17 target triangle identity changed at ${target.centerX},${target.centerZ}: ${tris.length} != ${target.expectedTriangles}`);const before=boxFor(THREE,mesh,pos,tris),gy=groundY(THREE,ground,target.centerX,target.centerZ,before.max.y),result=stretch(THREE,mesh,pos,tris,gy);done.push({target,tris,gy,...result});}pos.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere();mesh.updateMatrixWorld(true);model.updateWorldMatrix(true,true);let maxClear=base.maximumFinalClearanceMeters,maxDrift=base.maximumTopMountDriftMeters;for(const item of done){const b=boxFor(THREE,mesh,pos,item.tris),gy=groundY(THREE,ground,item.target.centerX,item.target.centerZ,b.max.y),clear=b.min.y-gy,drift=Math.abs(b.max.y-item.beforeTop);maxClear=Math.max(maxClear,Math.abs(clear));maxDrift=Math.max(maxDrift,drift);if(Math.abs(clear)>MAX_CLEAR)throw new Error(`A1 V17 final support clearance ${clear}`);if(drift>MAX_TOP_DRIFT)throw new Error(`A1 V17 support top drift ${drift}`);}const extraTris=done.reduce((s,d)=>s+d.tris.length,0),count=base.correctedSupportSetCount+done.length;model.userData.a1V17FinalWorldRodCorrection=Object.freeze({count:done.length,triangles:extraTris,maximumFinalClearanceMeters:maxClear,maximumTopMountDriftMeters:maxDrift});return Object.freeze({...base,correctedSupportSetCount:count,visibleLoadLegCount:count,remainingSuspendedSupportCount:0,maximumFinalClearanceMeters:maxClear,maximumTopMountDriftMeters:maxDrift,maximumExtensionMeters:Math.max(base.maximumExtensionMeters,...done.map(d=>d.extension)),secondaryMeshGroundedCount:base.secondaryMeshGroundedCount+done.length,secondaryMeshGroundedTriangleCount:base.secondaryMeshGroundedTriangleCount+extraTris,spatialRodClusterCount:base.spatialRodClusterCount+done.length,spatialRodTriangleCount:base.spatialRodTriangleCount+extraTris,spatialRodVertexCount:base.spatialRodVertexCount+extraTris*3,rampReferenceComponentCount:count,v17FinalWorldRodGroundedCount:done.length,v17FinalWorldRodTriangleCount:extraTris});}
export { A1_TUNNEL_C_VISIBLE_SUPPORT_GROUNDING_V3_AUTHORITY, A1_TUNNEL_C_VISIBLE_SUPPORT_SECONDARY_MESH_AUTHORITY } from "./a1TunnelCVisibleSupportGroundingV5.js";
