import { groundA1TunnelCVisibleSupportHardwareV3 as groundV14 } from "./a1TunnelCVisibleSupportGroundingV14.js";

const REGION = Object.freeze({ minX: -16, maxX: -8, minY: -1, maxY: 5, minZ: 6, maxZ: 14 });
const MESH_NAMES = Object.freeze(["Tunnel_B_Jetway_0", "Tunnel_C_Jetway_0"]);
const GROUND_NAMES = Object.freeze(["PHX_KPHX_SourceAuthoredPhotoGround_Tiled", "PHX_KPHX_SourceAuthoredPhotoGround"]);
const KEY_SCALE = 10000;
function rootOf(o){let r=o;while(r?.parent)r=r.parent;return r;}
function groundOf(root){for(const n of GROUND_NAMES){const g=root?.getObjectByName?.(n);if(g)return g;}throw new Error("A1 V16 no rendered pavement");}
function groundY(THREE,g,x,z,y){const ray=new THREE.Raycaster(new THREE.Vector3(x,y+40,z),new THREE.Vector3(0,-1,0));ray.far=200;return ray.intersectObject(g,true)[0]?.point?.y;}
function key(v){return `${Math.round(v.x*KEY_SCALE)},${Math.round(v.y*KEY_SCALE)},${Math.round(v.z*KEY_SCALE)}`;}
function inRegion(p){return p.x>=REGION.minX&&p.x<=REGION.maxX&&p.y>=REGION.minY&&p.y<=REGION.maxY&&p.z>=REGION.minZ&&p.z<=REGION.maxZ;}
function triangles(THREE,mesh,pos){const out=[],l=new THREE.Vector3(),w=new THREE.Vector3();for(let t=0;t<pos.count/3;t++){const pts=[];for(let c=0;c<3;c++){l.fromBufferAttribute(pos,t*3+c);pts.push(w.copy(l).applyMatrix4(mesh.matrixWorld).clone());}const centroid=new THREE.Vector3().add(pts[0]).add(pts[1]).add(pts[2]).multiplyScalar(1/3);if(!inRegion(centroid))continue;out.push({triangle:t,keys:pts.map(key),box:new THREE.Box3().setFromPoints(pts)});}return out;}
function cluster(items){const p=new Int32Array(items.length);for(let i=0;i<p.length;i++)p[i]=i;const find=i=>{let r=i;while(p[r]!==r)r=p[r];while(p[i]!==i){const n=p[i];p[i]=r;i=n;}return r;};const union=(a,b)=>{a=find(a);b=find(b);if(a!==b)p[b]=a;};const seen=new Map();for(let i=0;i<items.length;i++)for(const k of items[i].keys){const j=seen.get(k);if(j===undefined)seen.set(k,i);else union(i,j);}const m=new Map();for(let i=0;i<items.length;i++){const r=find(i);if(!m.has(r))m.set(r,[]);m.get(r).push(items[i]);}return [...m.values()];}
function bounds(THREE,g){const b=new THREE.Box3();for(const x of g)b.union(x.box);return b;}
export function groundA1TunnelCVisibleSupportHardwareV3(THREE,model){const base=groundV14(THREE,model),root=rootOf(model),ground=groundOf(root);root.updateWorldMatrix?.(true,true);model.updateWorldMatrix(true,true);const findings=[];for(const name of MESH_NAMES){const mesh=model?.getObjectByName?.(name);if(!mesh?.isMesh)continue;mesh.updateWorldMatrix(true,false);const geom=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone(),pos=geom.getAttribute("position");for(const group of cluster(triangles(THREE,mesh,pos))){const b=bounds(THREE,group),sx=b.max.x-b.min.x,sy=b.max.y-b.min.y,sz=b.max.z-b.min.z,c=b.getCenter(new THREE.Vector3()),gy=groundY(THREE,ground,c.x,c.z,b.max.y);if(!Number.isFinite(gy))continue;const clearance=b.min.y-gy;if(clearance>0.015&&clearance<1.6&&sx<=0.45&&sz<=0.45&&sy>=0.20&&sy<=2.2&&group.length>=2&&group.length<=220)findings.push({mesh:name,triangles:group.length,clearance:+clearance.toFixed(4),min:[+b.min.x.toFixed(4),+b.min.y.toFixed(4),+b.min.z.toFixed(4)],max:[+b.max.x.toFixed(4),+b.max.y.toFixed(4),+b.max.z.toFixed(4)],size:[+sx.toFixed(4),+sy.toFixed(4),+sz.toFixed(4)]});}}
findings.sort((a,b)=>b.clearance-a.clearance);throw new Error(`A1 V16 FINAL-WORLD NARROW SUPPORT DIAGNOSTIC ${JSON.stringify(findings)}`);
}
export { A1_TUNNEL_C_VISIBLE_SUPPORT_GROUNDING_V3_AUTHORITY, A1_TUNNEL_C_VISIBLE_SUPPORT_SECONDARY_MESH_AUTHORITY } from "./a1TunnelCVisibleSupportGroundingV5.js";
