import { groundA1TunnelCVisibleSupportHardwareV3 as groundV14 } from "./a1TunnelCVisibleSupportGroundingV14.js";

const REGION = Object.freeze({ minX: -18, maxX: -6, minY: -1, maxY: 5, minZ: 4, maxZ: 16 });
const MESH_NAMES = Object.freeze(["Tunnel_B_Jetway_0", "Tunnel_C_Jetway_0"]);
const GROUND_NAMES = Object.freeze(["PHX_KPHX_SourceAuthoredPhotoGround_Tiled", "PHX_KPHX_SourceAuthoredPhotoGround"]);
const CELL = 0.12;
function rootOf(o){let r=o;while(r?.parent)r=r.parent;return r;}
function groundOf(root){for(const n of GROUND_NAMES){const g=root?.getObjectByName?.(n);if(g)return g;}throw new Error("A1 V16 no rendered pavement");}
function groundY(THREE,g,x,z,y){const ray=new THREE.Raycaster(new THREE.Vector3(x,y+40,z),new THREE.Vector3(0,-1,0));ray.far=200;return ray.intersectObject(g,true)[0]?.point?.y;}
function inRegion(p){return p.x>=REGION.minX&&p.x<=REGION.maxX&&p.y>=REGION.minY&&p.y<=REGION.maxY&&p.z>=REGION.minZ&&p.z<=REGION.maxZ;}
export function groundA1TunnelCVisibleSupportHardwareV3(THREE,model){groundV14(THREE,model);const root=rootOf(model),ground=groundOf(root);root.updateWorldMatrix?.(true,true);model.updateWorldMatrix(true,true);const findings=[];for(const name of MESH_NAMES){const mesh=model?.getObjectByName?.(name);if(!mesh?.isMesh)continue;mesh.updateWorldMatrix(true,false);const geom=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone(),pos=geom.getAttribute("position"),l=new THREE.Vector3(),w=new THREE.Vector3(),cells=new Map();for(let t=0;t<pos.count/3;t++){const pts=[];for(let c=0;c<3;c++){l.fromBufferAttribute(pos,t*3+c);pts.push(w.copy(l).applyMatrix4(mesh.matrixWorld).clone());}const cx=(pts[0].x+pts[1].x+pts[2].x)/3,cy=(pts[0].y+pts[1].y+pts[2].y)/3,cz=(pts[0].z+pts[1].z+pts[2].z)/3,centroid=new THREE.Vector3(cx,cy,cz);if(!inRegion(centroid))continue;const ix=Math.floor(cx/CELL),iz=Math.floor(cz/CELL),k=`${ix},${iz}`;let cell=cells.get(k);if(!cell){cell={ix,iz,count:0,minY:Infinity,maxY:-Infinity,minX:Infinity,maxX:-Infinity,minZ:Infinity,maxZ:-Infinity};cells.set(k,cell);}cell.count++;for(const p of pts){cell.minY=Math.min(cell.minY,p.y);cell.maxY=Math.max(cell.maxY,p.y);cell.minX=Math.min(cell.minX,p.x);cell.maxX=Math.max(cell.maxX,p.x);cell.minZ=Math.min(cell.minZ,p.z);cell.maxZ=Math.max(cell.maxZ,p.z);}}
for(const cell of cells.values()){const x=(cell.ix+0.5)*CELL,z=(cell.iz+0.5)*CELL,gy=groundY(THREE,ground,x,z,cell.maxY);if(!Number.isFinite(gy))continue;const clearance=cell.minY-gy,span=cell.maxY-cell.minY;if(clearance>0.04&&clearance<1.8&&span>0.28&&cell.count>=2)findings.push({mesh:name,cell:[cell.ix,cell.iz],center:[+x.toFixed(3),+z.toFixed(3)],triangles:cell.count,clearance:+clearance.toFixed(4),y:[+cell.minY.toFixed(4),+cell.maxY.toFixed(4)],span:+span.toFixed(4),xz:[+cell.minX.toFixed(4),+cell.maxX.toFixed(4),+cell.minZ.toFixed(4),+cell.maxZ.toFixed(4)]});}}
findings.sort((a,b)=>b.span-a.span||b.clearance-a.clearance);throw new Error(`A1 V16 RENDER-SPACE COLUMN DIAGNOSTIC ${JSON.stringify(findings.slice(0,80))}`);}
export { A1_TUNNEL_C_VISIBLE_SUPPORT_GROUNDING_V3_AUTHORITY, A1_TUNNEL_C_VISIBLE_SUPPORT_SECONDARY_MESH_AUTHORITY } from "./a1TunnelCVisibleSupportGroundingV5.js";
