import { groundA1TunnelCVisibleSupportHardwareV3 as groundV13 } from "./a1TunnelCVisibleSupportGroundingV13.js";

const GROUND_NAMES = Object.freeze(["PHX_KPHX_SourceAuthoredPhotoGround_Tiled", "PHX_KPHX_SourceAuthoredPhotoGround"]);
const TARGETS = Object.freeze([
  Object.freeze({ name: "outboard-a", minX: -11.31, maxX: -11.20, minZ: 10.04, maxZ: 10.17 }),
  Object.freeze({ name: "outboard-b", minX: -13.10, maxX: -13.00, minZ: 10.27, maxZ: 10.40 }),
]);
const MAX_FINAL_CLEARANCE = 0.015;
const MAX_TOP_DRIFT = 0.015;
const MAX_EXTENSION = 1.55;
function rootOf(o){let r=o;while(r?.parent)r=r.parent;return r;}
function groundOf(root){for(const n of GROUND_NAMES){const g=root?.getObjectByName?.(n);if(g)return g;}throw new Error("A1 V19 no rendered pavement");}
function groundY(THREE,g,x,z,y){const r=new THREE.Raycaster(new THREE.Vector3(x,y+40,z),new THREE.Vector3(0,-1,0));r.far=200;const hit=r.intersectObject(g,true)[0];if(!hit?.point)throw new Error(`A1 V19 pavement ray miss ${x},${z}`);return hit.point.y;}
function triWorld(THREE,mesh,pos,t){const l=new THREE.Vector3(),w=new THREE.Vector3(),pts=[];for(let c=0;c<3;c++){l.fromBufferAttribute(pos,t*3+c);pts.push(w.copy(l).applyMatrix4(mesh.matrixWorld).clone());}return pts;}
function collect(THREE,mesh,pos,target){const ids=[];for(let t=0;t<pos.count/3;t++){const pts=triWorld(THREE,mesh,pos,t),box=new THREE.Box3().setFromPoints(pts),c=box.getCenter(new THREE.Vector3());const sx=box.max.x-box.min.x,sy=box.max.y-box.min.y,sz=box.max.z-box.min.z;if(c.x<target.minX||c.x>target.maxX||c.z<target.minZ||c.z>target.maxZ)continue;if(sx>0.12||sz>0.14||sy<0.05)continue;ids.push(t);}return ids;}
function bounds(THREE,mesh,pos,ids){const b=new THREE.Box3();for(const t of ids)for(const p of triWorld(THREE,mesh,pos,t))b.expandByPoint(p);return b;}
function stretch(THREE,mesh,pos,ids,rampY){const before=bounds(THREE,mesh,pos,ids),min=before.min.y,max=before.max.y,h=max-min,ext=min-rampY;if(ids.length<24||ids.length>400)throw new Error(`A1 V19 implausible complete rod triangle count ${ids.length}`);if(!(h>0.30&&h<1.40))throw new Error(`A1 V19 implausible complete rod height ${h}`);if(!(ext>MAX_FINAL_CLEARANCE&&ext<=MAX_EXTENSION))throw new Error(`A1 V19 rod extension out of range ${ext}`);const inv=mesh.matrixWorld.clone().invert(),l=new THREE.Vector3(),w=new THREE.Vector3();for(const t of ids)for(let c=0;c<3;c++){const i=t*3+c;l.fromBufferAttribute(pos,i);w.copy(l).applyMatrix4(mesh.matrixWorld);const f=Math.max(0,Math.min(1,(w.y-min)/h));w.y=rampY+f*(max-rampY);l.copy(w).applyMatrix4(inv);pos.setXYZ(i,l.x,l.y,l.z);}return {beforeTop:max,extension:ext,count:ids.length};}
export function groundA1TunnelCVisibleSupportHardwareV3(THREE,model){const base=groundV13(THREE,model),root=rootOf(model),ground=groundOf(root),mesh=model?.getObjectByName?.("Tunnel_B_Jetway_0");if(!mesh?.isMesh)throw new Error("A1 V19 no Tunnel_B_Jetway_0");root.updateWorldMatrix?.(true,true);model.updateWorldMatrix(true,true);mesh.updateWorldMatrix(true,false);mesh.geometry=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();const pos=mesh.geometry.getAttribute("position"),done=[];for(const target of TARGETS){const ids=collect(THREE,mesh,pos,target);const before=bounds(THREE,mesh,pos,ids),cx=(target.minX+target.maxX)/2,cz=(target.minZ+target.maxZ)/2,gy=groundY(THREE,ground,cx,cz,before.max.y),r=stretch(THREE,mesh,pos,ids,gy);done.push({target,ids,gy,...r});}pos.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere();mesh.updateMatrixWorld(true);model.updateWorldMatrix(true,true);let maxClear=base.maximumFinalClearanceMeters,maxDrift=base.maximumTopMountDriftMeters;for(const d of done){const b=bounds(THREE,mesh,pos,d.ids),cx=(d.target.minX+d.target.maxX)/2,cz=(d.target.minZ+d.target.maxZ)/2,gy=groundY(THREE,ground,cx,cz,b.max.y),clear=b.min.y-gy,drift=Math.abs(b.max.y-d.beforeTop);maxClear=Math.max(maxClear,Math.abs(clear));maxDrift=Math.max(maxDrift,drift);if(Math.abs(clear)>MAX_FINAL_CLEARANCE)throw new Error(`A1 V19 final rod clearance ${d.target.name} ${clear}`);if(drift>MAX_TOP_DRIFT)throw new Error(`A1 V19 top drift ${d.target.name} ${drift}`);}const triangles=done.reduce((s,d)=>s+d.count,0),count=base.correctedSupportSetCount+done.length;model.userData.a1V19CompleteTunnelBRods=Object.freeze({count:done.length,triangles,maximumFinalClearanceMeters:maxClear,maximumTopMountDriftMeters:maxDrift});return Object.freeze({...base,correctedSupportSetCount:count,visibleLoadLegCount:count,remainingSuspendedSupportCount:0,maximumFinalClearanceMeters:maxClear,maximumTopMountDriftMeters:maxDrift,maximumExtensionMeters:Math.max(base.maximumExtensionMeters,...done.map(d=>d.extension)),secondaryMeshGroundedCount:base.secondaryMeshGroundedCount+done.length,secondaryMeshGroundedTriangleCount:base.secondaryMeshGroundedTriangleCount+triangles,spatialRodClusterCount:base.spatialRodClusterCount+done.length,spatialRodTriangleCount:base.spatialRodTriangleCount+triangles,spatialRodVertexCount:base.spatialRodVertexCount+triangles*3,rampReferenceComponentCount:count,v19CompleteRodGroundedCount:done.length,v19CompleteRodTriangleCount:triangles});}
export { A1_TUNNEL_C_VISIBLE_SUPPORT_GROUNDING_V3_AUTHORITY, A1_TUNNEL_C_VISIBLE_SUPPORT_SECONDARY_MESH_AUTHORITY } from "./a1TunnelCVisibleSupportGroundingV5.js";
