// GENERATED by scripts/prepare-terminal4-runtime.mjs. Do not edit directly.
import React, { useCallback, useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { buildCRJ700Aircraft } from "./aircraft/crj700Model.js";
import { JACKKNIFE_WARNING, createPushbackState, stepPushbackDynamics } from "../simulation/pushbackDynamics.js";
import {
  CONNECTION_PHASES,
  beginTow,
  connectionAllowsMotion,
  connectionHasAircraft,
  createConnectionState,
  requestCapture,
  requestLower,
  stepConnection,
} from "../simulation/noseGearConnection.js";
import { createProceduralLektroRig, validateTugRig } from "../tug/lektroRig.js";
import { installRuntimeEquipmentVisual, supportsRuntimeEquipmentVisual } from "../tug/runtimeEquipmentVisual.js";
import { buildKphxExactLiveEnvironment as buildTerminal4RampEnvironment, installKphxExactLiveTerminal4 as installAuthoredTerminal4Visual } from "../environment/kphxFullAirport/installLiveTerminal4Exact.js";
import { installKphxPackageOwnedSurfaceLayer } from "../environment/kphxFullAirport/installPackageOwnedSurfaceLayer.js";
import { KPHX_FULL_AIRPORT_SOURCE, kphxXPlaneHeadingToRampReadyYawRadians } from "../environment/kphxFullAirport/sourceAuthority.js";
import { KPHX_T4_GATE_POSE_SOURCE, createKphxTerminal4GateScenarioPose } from "../environment/kphxFullAirport/terminal4GatePoseAuthority.js";
import "./RampReadyTrainer.css";
import "./procedure-gates.css";
import "./mobile-runtime-recovery.css";
import "./inspection-compact-v30.css";
import "./mobile-hud-v9.css";

const A1_SCENARIO_POSE = createKphxTerminal4GateScenarioPose(
  KPHX_FULL_AIRPORT_SOURCE.anchor.wedObjectId,
  { equipmentApproachOffsetMeters: 6.2 },
);
if (A1_SCENARIO_POSE.gate !== "A1") throw new Error("Exact KPHX A1 WED gate scenario pose is missing");
const A1_AIRCRAFT_START_X = A1_SCENARIO_POSE.aircraft.x;
const NOSE_START_Z = A1_SCENARIO_POSE.aircraft.z;
const STOP_Z = 52;
const A1_AIRCRAFT_HEADING_AUTHORITY = "KPHX-1.75.1-earth.wed.xml-WED_RampPosition-27855";
const A1_SOURCE_HEADING_DEGREES = A1_SCENARIO_POSE.sourceHeadingDegrees;
const A1_AIRCRAFT_YAW_RADIANS = A1_SCENARIO_POSE.aircraft.yaw;
const A1_EQUIPMENT_APPROACH_OFFSET_METERS = A1_SCENARIO_POSE.equipmentApproachOffsetMeters;
const A1_EQUIPMENT_SPAWN_AUTHORITY = A1_SCENARIO_POSE.authority;
const A1_EQUIPMENT_SPAWN = A1_SCENARIO_POSE.equipment;
function createA1SpawnPushbackState() {
  return createPushbackState({
    tugX: A1_EQUIPMENT_SPAWN.x,
    tugZ: A1_EQUIPMENT_SPAWN.z,
    tugYaw: A1_EQUIPMENT_SPAWN.yaw,
    aircraftX: A1_AIRCRAFT_START_X,
    aircraftZ: NOSE_START_Z,
    aircraftYaw: A1_AIRCRAFT_YAW_RADIANS,
  });
}
const STAGES = [
  "Complete visual equipment check",
  "Align the capture head with the nose gear",
  "Capture and secure the nose gear",
  "Request pushback clearance",
  "Confirm aircraft parking brake released",
  "Push back and stop at the red line",
  "Lower and release the nose gear",
  "Drive the tug clear",
  "Scenario complete",
];
const INSPECTION_PRESETS = Object.freeze({
  // Each chase camera is placed on the apron side of its tug and looks back
  // toward the actual source jetway/terminal position instead of across an
  // empty taxiway. Positions remain source-gate apron locations.
  a1: Object.freeze({ id: "a1", label: "A1 ramp", x: A1_EQUIPMENT_SPAWN.x, z: A1_EQUIPMENT_SPAWN.z, yaw: A1_EQUIPMENT_SPAWN.yaw, cameraYaw: 0.92, cameraDistance: 25 }),
  // A true side-on architectural view of the measured A1 rotunda-to-T4_WALK
  // corridor. The tug remains freely drivable and the driver/overhead views
  // remain available, while chase mode starts by looking directly at the joint
  // rather than hiding it behind the rotunda.
  a1Connection: Object.freeze({
    id: "a1Connection",
    label: "A1 terminal connection",
    x: 7.5,
    z: 8.5,
    yaw: -0.35,
    cameraYaw: 0,
    cameraDistance: 22,
    cameraPosition: Object.freeze([-12.0, 10.5, 28.0]),
    cameraTarget: Object.freeze([-27.5, 4.1, -16.15]),
  }),
  a14: Object.freeze({ id: "a14", label: "A concourse midpoint", x: 218.45, z: -86.52, yaw: 2.88, cameraYaw: 2.19, cameraDistance: 32 }),
  b14: Object.freeze({ id: "b14", label: "B concourse midpoint", x: 216.4, z: 150.35, yaw: 2.8, cameraYaw: 2.10, cameraDistance: 32 }),
  // B15 sits on the east face of the north-south pier. The former inspection
  // pose faced south toward the distant main concourse and could not verify the
  // B15L/B15M terminal portals. This pose is on the actual B15 apron, 21.85 m
  // east of the facade, and points the operator view directly west at both gates.
  b15: Object.freeze({ id: "b15", label: "B15 ramp", x: -18.5, z: 539.2, yaw: -1.5708, cameraYaw: 1.38, cameraDistance: 25 }),
});
const INSPECTION_ROUTE_AUTHORITY = "source-gate-apron-presets-with-wide-diagonal-a1-connection-near-wall-b15-a1-a14-b14-b15-v7";
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

function material(color, roughness = 0.62, metalness = 0.05) {
  return new THREE.MeshStandardMaterial({ color, roughness, metalness });
}

function cylinder(radius, depth, color, x, y, z, rx = 0, ry = 0, rz = 0) {
  const mesh = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius, depth, 32), material(color, 0.78, 0.04));
  mesh.position.set(x, y, z);
  mesh.rotation.set(rx, ry, rz);
  mesh.castShadow = true;
  mesh.receiveShadow = true;
  return mesh;
}

function buildGround(scene) {
  const environment = buildTerminal4RampEnvironment(THREE);
  environment.position.set(0, 0, 0);
  scene.add(environment);
  return environment;
}
function connectionMetrics(sim) {
  const cradle = sim.rig.getCaptureWorld(new THREE.Vector3());
  const delta = sim.aircraft.position.clone().sub(cradle);
  const forward = new THREE.Vector3(Math.sin(sim.rig.root.rotation.y), 0, Math.cos(sim.rig.root.rotation.y));
  const right = new THREE.Vector3(Math.cos(sim.rig.root.rotation.y), 0, -Math.sin(sim.rig.root.rotation.y));
  const heading = Math.abs(Math.atan2(
    Math.sin(sim.aircraft.rotation.y - sim.rig.root.rotation.y),
    Math.cos(sim.aircraft.rotation.y - sim.rig.root.rotation.y),
  ));
  return {
    cradle,
    distance: delta.length(),
    lateral: Math.abs(delta.dot(right)),
    heading,
    speed: Math.abs(sim.dynamics.speed),
    fromFront: delta.dot(forward) >= -0.05,
  };
}

function dispose(object) {
  object.traverse((child) => {
    child.geometry?.dispose?.();
    if (Array.isArray(child.material)) child.material.forEach((entry) => entry.dispose());
    else child.material?.dispose?.();
  });
}

export default function RampReadyStandupTrainer({
  equipmentId = "lektro-88",
  initialInspectionMode = false,
  onChangeEquipment,
  gyroAvailable = true,
  gyroEnabled = false,
  onToggleGyro,
}) {
  const mountRef = useRef(null);
  const simRef = useRef(null);
  const stageRef = useRef(0);
  const cameraRef = useRef("chase");
  const inspectionRef = useRef(false);
  const inspectionPresetRef = useRef("a1");
  const jetwayRef = useRef({
    controller: null,
    deployment: 1,
    target: 1,
    retractionRequested: false,
    transitionStartDeployment: 1,
    transitionStartedAt: 0,
    transitionDurationMs: 15000,
  });
  const orbitRef = useRef({
    yaw: -0.64,
    pitch: 0.38,
    distance: 16,
    pointerId: null,
    lastX: 0,
    lastY: 0,
  });
  const driveRef = useRef({ throttle: 0, steer: 0, brake: false, direction: 1 });
  const keysRef = useRef(new Set());
  const scoreRef = useRef(100);
  const [stage, setStage] = useState(0);
  const [cameraMode, setCameraMode] = useState("chase");
  const [inspectionMode, setInspectionMode] = useState(false);
  const [inspectionPreset, setInspectionPreset] = useState("a1");
  const [direction, setDirection] = useState("FWD");
  const [throttle, setThrottle] = useState(0);
  const [message, setMessage] = useState("Complete the equipment check, then approach at idle speed.");
  const [hud, setHud] = useState({
    speed: 0,
    stop: STOP_Z - NOSE_START_Z,
    capture: 0,
    ready: false,
    articulation: 0,
    warning: false,
    score: 100,
    phase: CONNECTION_PHASES.APPROACH,
    progress: 0,
    tug: equipmentId,
    aircraft: "loading",
  });

  useEffect(() => { stageRef.current = stage; }, [stage]);
  useEffect(() => { cameraRef.current = cameraMode; }, [cameraMode]);
  useEffect(() => { inspectionPresetRef.current = inspectionPreset; }, [inspectionPreset]);
  useEffect(() => {
    inspectionRef.current = inspectionMode;
    const canvas = simRef.current?.renderer?.domElement;
    if (canvas) canvas.dataset.inspectionMode = inspectionMode ? "active" : "training";
  }, [inspectionMode]);

  const reset = useCallback(() => {
    const sim = simRef.current;
    if (!sim) return;
    sim.connection = createConnectionState();
    sim.dynamics = createA1SpawnPushbackState();
    sim.rig.root.position.set(A1_EQUIPMENT_SPAWN.x, 0, A1_EQUIPMENT_SPAWN.z);
    sim.rig.root.rotation.y = A1_EQUIPMENT_SPAWN.yaw;
    sim.rig.setSteering(0);
    sim.rig.setLiftProgress(0);
    sim.aircraft.position.set(A1_AIRCRAFT_START_X, 0, NOSE_START_Z);
    sim.aircraft.rotation.y = A1_AIRCRAFT_YAW_RADIANS;
    const resetJetwayDeployment = inspectionRef.current ? 0 : 1;
    jetwayRef.current.target = resetJetwayDeployment;
    jetwayRef.current.deployment = resetJetwayDeployment;
    jetwayRef.current.transitionStartDeployment = resetJetwayDeployment;
    jetwayRef.current.transitionStartedAt = 0;
    jetwayRef.current.retractionRequested = false;
    jetwayRef.current.controller?.setDeployment(resetJetwayDeployment);
    driveRef.current = { throttle: 0, steer: 0, brake: false, direction: 1 };
    orbitRef.current.yaw = -0.64;
    orbitRef.current.pitch = 0.38;
    orbitRef.current.distance = 16;
    scoreRef.current = 100;
    stageRef.current = 0;
    setStage(0);
    setThrottle(0);
    setDirection("FWD");
    setMessage(inspectionRef.current
      ? "Free-drive inspection reset at A1. Use the tug to inspect any part of the airport."
      : "Complete the equipment check, then approach at idle speed.");
  }, []);

  const moveInspectionToPreset = useCallback((presetId) => {
    const preset = INSPECTION_PRESETS[presetId] || INSPECTION_PRESETS.a1;
    inspectionPresetRef.current = preset.id;
    setInspectionPreset(preset.id);
    const sim = simRef.current;
    if (!sim) return;
    sim.connection = createConnectionState();
    sim.dynamics = createPushbackState({
      tugX: preset.x,
      tugZ: preset.z,
      tugYaw: preset.yaw,
      aircraftX: sim.aircraft.position.x,
      aircraftZ: sim.aircraft.position.z,
      aircraftYaw: sim.aircraft.rotation.y,
    });
    sim.rig.root.position.set(preset.x, 0, preset.z);
    sim.rig.root.rotation.y = preset.yaw;
    sim.rig.setSteering(0);
    sim.rig.setLiftProgress(0);
    driveRef.current = { throttle: 0, steer: 0, brake: false, direction: 1 };
    orbitRef.current.yaw = preset.cameraYaw;
    orbitRef.current.pitch = 0.38;
    orbitRef.current.distance = preset.cameraDistance || 30;
    scoreRef.current = 100;
    setThrottle(0);
    setDirection("FWD");
    setCameraMode("chase");
    const canvas = sim.renderer.domElement;
    canvas.dataset.inspectionPreset = preset.id;
    canvas.dataset.inspectionPresetLabel = preset.label;
    canvas.dataset.inspectionRouteAuthority = INSPECTION_ROUTE_AUTHORITY;
    canvas.dataset.inspectionTugX = preset.x.toFixed(3);
    canvas.dataset.inspectionTugZ = preset.z.toFixed(3);
    canvas.dataset.cameraYaw = preset.cameraYaw.toFixed(4);
    canvas.dataset.cameraPitch = orbitRef.current.pitch.toFixed(4);
    canvas.dataset.cameraDistance = orbitRef.current.distance.toFixed(3);
    canvas.dataset.inspectionCameraAuthority = preset.cameraPosition
      ? "wide-diagonal-a1-terminal-joint-v6-clear-tug"
      : "free-orbit-follow-tug";
    setMessage(`Inspection position: ${preset.label}. Drive freely with W/S or the power slider and use A/D to steer.`);
  }, []);

  const toggleInspectionDrive = useCallback(() => {
    const next = !inspectionRef.current;
    inspectionRef.current = next;
    setInspectionMode(next);
    const sim = simRef.current;
    if (sim) {
      sim.connection = createConnectionState();
      sim.dynamics = createA1SpawnPushbackState();
      sim.rig.root.position.set(A1_EQUIPMENT_SPAWN.x, 0, A1_EQUIPMENT_SPAWN.z);
      sim.rig.root.rotation.y = A1_EQUIPMENT_SPAWN.yaw;
      sim.rig.setSteering(0);
      sim.rig.setLiftProgress(0);
      sim.aircraft.position.set(A1_AIRCRAFT_START_X, 0, NOSE_START_Z);
      sim.aircraft.rotation.y = A1_AIRCRAFT_YAW_RADIANS;
      sim.renderer.domElement.dataset.inspectionMode = next ? "active" : "training";
      sim.renderer.domElement.dataset.inspectionPreset = next ? "a1" : "training";
      sim.renderer.domElement.dataset.inspectionPresetLabel = next ? INSPECTION_PRESETS.a1.label : "Training";
      sim.renderer.domElement.dataset.inspectionRouteAuthority = INSPECTION_ROUTE_AUTHORITY;
      const inspectionJetwayDeployment = next ? 0 : 1;
      jetwayRef.current.target = inspectionJetwayDeployment;
      jetwayRef.current.deployment = inspectionJetwayDeployment;
      jetwayRef.current.transitionStartDeployment = inspectionJetwayDeployment;
      jetwayRef.current.transitionStartedAt = 0;
      jetwayRef.current.retractionRequested = false;
      jetwayRef.current.controller?.setDeployment(inspectionJetwayDeployment);
    }
    driveRef.current = { throttle: 0, steer: 0, brake: false, direction: 1 };
    orbitRef.current.yaw = -0.64;
    orbitRef.current.pitch = 0.38;
    orbitRef.current.distance = next ? 20 : 16;
    scoreRef.current = 100;
    stageRef.current = 0;
    setStage(0);
    setThrottle(0);
    setDirection("FWD");
    setCameraMode("chase");
    inspectionPresetRef.current = "a1";
    setInspectionPreset("a1");
    setMessage(next
      ? "Free-drive airport inspection active. Use W/S or the power slider, A/D to steer, and the camera views to inspect the entire airport."
      : "Training mode restored. Complete the equipment check, then approach at idle speed.");
  }, []);

  useEffect(() => {
    if (!initialInspectionMode) return undefined;
    let cancelled = false;
    let frameId = 0;
    let attempts = 0;
    const activate = () => {
      if (cancelled) return;
      attempts += 1;
      if (simRef.current) {
        if (!inspectionRef.current) toggleInspectionDrive();
        return;
      }
      if (attempts < 600) frameId = window.requestAnimationFrame(activate);
    };
    frameId = window.requestAnimationFrame(activate);
    return () => {
      cancelled = true;
      window.cancelAnimationFrame(frameId);
    };
  }, [initialInspectionMode, toggleInspectionDrive]);

  const advance = useCallback(() => {
    const sim = simRef.current;
    if (!sim || inspectionRef.current) return;
    if (stageRef.current === 0) {
      if (jetwayRef.current.retractionRequested) return;
      jetwayRef.current.transitionStartDeployment = jetwayRef.current.deployment;
      jetwayRef.current.transitionStartedAt = performance.now();
      jetwayRef.current.target = 0;
      jetwayRef.current.retractionRequested = true;
      setMessage("Jetway departure active: AutoGate disengage is retracting the exact A1 tunnel and rotating the cabin to park.");
    } else if (stageRef.current === 3 && sim.connection.phase === CONNECTION_PHASES.SECURED) {
      stageRef.current = 4;
      setStage(4);
      setMessage("Clearance received. Confirm aircraft parking brake release.");
    } else if (stageRef.current === 4 && sim.connection.phase === CONNECTION_PHASES.SECURED) {
      sim.connection = beginTow(sim.connection);
      stageRef.current = 5;
      setStage(5);
      setMessage("Brake released. Add power gradually and steer smoothly.");
    }
  }, []);

  const capture = useCallback(() => {
    const sim = simRef.current;
    if (!sim || inspectionRef.current || stageRef.current !== 1) return;
    sim.connection = requestCapture(sim.connection, connectionMetrics(sim));
    driveRef.current.throttle = 0;
    setThrottle(0);
    if (sim.connection.phase === CONNECTION_PHASES.CAPTURING) {
      stageRef.current = 2;
      setStage(2);
    }
    setMessage(sim.connection.reason);
  }, []);

  const lower = useCallback(() => {
    const sim = simRef.current;
    if (!sim || inspectionRef.current || stageRef.current !== 6) return;
    sim.connection = requestLower(sim.connection, sim.dynamics.speed, sim.dynamics.articulation);
    driveRef.current.throttle = 0;
    setThrottle(0);
    setMessage(sim.connection.reason);
  }, []);

  const setPower = useCallback((value) => {
    const normalized = clamp(Number(value) || 0, 0, 100);
    setThrottle(normalized);
    driveRef.current.throttle = normalized / 100;
  }, []);

  useEffect(() => {
    if (!supportsRuntimeEquipmentVisual(equipmentId)) throw new Error(`Unsupported runtime equipment: ${equipmentId}`);
    const mount = mountRef.current;
    if (!mount) return undefined;

    const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: "high-performance" });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
    renderer.shadowMap.enabled = true;
    renderer.domElement.className = "trainerCanvas";
    renderer.domElement.dataset.cameraYaw = orbitRef.current.yaw.toFixed(4);
    renderer.domElement.dataset.cameraPitch = orbitRef.current.pitch.toFixed(4);
    renderer.domElement.dataset.cameraDistance = orbitRef.current.distance.toFixed(3);
    renderer.domElement.dataset.equipmentId = equipmentId;
    renderer.domElement.dataset.inspectionMode = inspectionRef.current ? "active" : "training";
    renderer.domElement.dataset.inspectionPreset = inspectionRef.current ? inspectionPresetRef.current : "training";
    renderer.domElement.dataset.inspectionPresetLabel = inspectionRef.current
      ? (INSPECTION_PRESETS[inspectionPresetRef.current] || INSPECTION_PRESETS.a1).label
      : "Training";
    renderer.domElement.dataset.inspectionRouteAuthority = INSPECTION_ROUTE_AUTHORITY;
    mount.replaceChildren(renderer.domElement);

    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x9fc4e6);
    scene.fog = new THREE.Fog(0x9fc4e6, 2400, 6500);
    scene.add(new THREE.HemisphereLight(0xffffff, 0x58616b, 1.45));
    const sun = new THREE.DirectionalLight(0xffffff, 2.1);
    sun.position.set(18, 28, -14);
    sun.castShadow = true;
    scene.add(sun);
    const environment = buildGround(scene);
    const airportCollision = {
      authority: "terminal-jetway-aircraft-raycast-envelope-v45",
      raycaster: new THREE.Raycaster(),
      direction: new THREE.Vector3(),
      origin: new THREE.Vector3(),
      staticTargets: [],
      aircraftTarget: null,
      ready: false,
      blocked: false,
      count: 0,
      lastMessageAt: 0,
    };
    const collisionHierarchyVisible = (object) => {
      for (let current = object; current; current = current.parent) {
        if (current.visible === false) return false;
      }
      return true;
    };
    const collisionHitEligible = (hit) => {
      if (!hit?.object?.isMesh || !collisionHierarchyVisible(hit.object)) return false;
      const path = [];
      for (let current = hit.object; current; current = current.parent) path.push(current.name || "");
      const identity = path.join("/");
      if (/Ground|Aerial|Pavement|Marking|Projected|Runway|Taxiway|LightHalo|ApronSurface/i.test(identity)) return false;
      if (hit.object.material?.transparent && Number(hit.object.material.opacity) <= 0.05) return false;
      return Number(hit.point?.y) >= 0.18;
    };
    const airportMovementBlocked = ({ startX, startZ, endX, endZ, radius, heights, includeAircraft = false }) => {
      if (!airportCollision.ready) return false;
      const dx = endX - startX;
      const dz = endZ - startZ;
      const distance = Math.hypot(dx, dz);
      if (!(distance > 0.0005)) return false;
      airportCollision.direction.set(dx / distance, 0, dz / distance);
      const sideX = -airportCollision.direction.z;
      const sideZ = airportCollision.direction.x;
      const targets = includeAircraft && airportCollision.aircraftTarget
        ? [...airportCollision.staticTargets, airportCollision.aircraftTarget]
        : airportCollision.staticTargets;
      const rayLength = distance + radius + 0.2;
      const probes = [
        { side: -0.82, height: heights[0] },
        { side: 0, height: heights[0] },
        { side: 0.82, height: heights[0] },
        { side: 0, height: heights[1] },
        { side: 0, height: heights[2] },
      ];
      for (const probe of probes) {
        airportCollision.origin.set(
          startX + sideX * radius * probe.side,
          probe.height,
          startZ + sideZ * radius * probe.side,
        );
        airportCollision.raycaster.set(airportCollision.origin, airportCollision.direction);
        airportCollision.raycaster.near = 0.04;
        airportCollision.raycaster.far = rayLength;
        const hit = airportCollision.raycaster
          .intersectObjects(targets, true)
          .find(collisionHitEligible);
        if (hit) return true;
      }
      return false;
    };
    const aircraftCollisionSamples = (x, z, yaw) => {
      const local = [
        [0, 0],
        [0, 8.5],
        [0, 17.5],
        [0, 26.5],
        [-10.8, 12.5],
        [10.8, 12.5],
      ];
      const sin = Math.sin(yaw);
      const cos = Math.cos(yaw);
      return local.map(([side, longitudinal]) => ({
        x: x + cos * side + sin * longitudinal,
        z: z - sin * side + cos * longitudinal,
      }));
    };
    renderer.domElement.dataset.airportCollisionAuthority = airportCollision.authority;
    renderer.domElement.dataset.airportCollisionReady = "false";
    renderer.domElement.dataset.airportCollisionTargetCount = "0";
    renderer.domElement.dataset.airportCollisionState = "clear";
    renderer.domElement.dataset.airportCollisionCount = "0";
    renderer.domElement.dataset.airportCollisionAircraftEnvelope = "nose-center-tail-wing-sweep-v2";
    renderer.domElement.dataset.environmentSource = "loading-authored-phx-terminal4-textured";
    renderer.domElement.dataset.groundSource = "loading-authored-kphx-v181";
    renderer.domElement.dataset.photoGroundSource = "loading-source-authored-phx-photo";
    renderer.domElement.dataset.kphxVersion = "loading";
    renderer.domElement.dataset.kphxDetailLevel = "loading";
    renderer.domElement.dataset.photoDetailLevel = "loading";
    renderer.domElement.dataset.photoTextureMode = "loading";
    renderer.domElement.dataset.photoRuntimeTileCount = "loading";
    renderer.domElement.dataset.photoMaxTextureDimension = "loading";
    renderer.domElement.dataset.photoTileCount = "loading";
    renderer.domElement.dataset.photoWidth = "loading";
    renderer.domElement.dataset.photoHeight = "loading";
    renderer.domElement.dataset.photoBytes = "loading";
    renderer.domElement.dataset.hiddenAdexSurfaceMaterials = "loading";
    renderer.domElement.dataset.b15Anchors = "loading";
    renderer.domElement.dataset.b15CorridorMeters = "loading";
    renderer.domElement.dataset.terminal4TextureCount = "loading";
    renderer.domElement.dataset.terminal4ExactTextureCount = "loading";
    renderer.domElement.dataset.terminal4A1LegacyBlockRemovedTriangles = "loading";
    renderer.domElement.dataset.terminal4A1LegacyBlockAuthority = "loading";
    renderer.domElement.dataset.terminal4FallbackTextureCount = "loading";
    renderer.domElement.dataset.terminal4TexturedMaterialCount = "loading";
    renderer.domElement.dataset.terminal4Position = "loading";
    renderer.domElement.dataset.terminal4A1NearestGeometryMeters = "loading";
    renderer.domElement.dataset.terminal4Placement = "loading";
    renderer.domElement.dataset.terminal4A1JetwayWallDistance = "loading";
    renderer.domElement.dataset.terminal4JetwaySourceScaleAuthority = "loading";
    renderer.domElement.dataset.terminal4JetwaySourceGeometryMode = "loading";
    renderer.domElement.dataset.terminal4RequiresOriginalJetwayMesh = "loading";
    renderer.domElement.dataset.terminal4JetwayInitialState = "loading";
    renderer.domElement.dataset.terminal4JetwayPrePushSequence = "loading";
    renderer.domElement.dataset.a1JetwayDeployment = "loading";
    renderer.domElement.dataset.a1JetwayState = "loading";
    renderer.domElement.dataset.a1JetwayAnimationAuthority = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayLoadState = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayCount = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayConnectorCount = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayVerifiedModelCount = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayReadyAuthority = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayArticulationAuthority = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwaySourceContactDistanceMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayStaticArticulatedGateCount = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayStaticMaximumContactErrorMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1TargetDoorDistanceMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1AttachedExtensionMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1PredictedDoorGapMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1PredictedContactDistanceMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1ActualContactDistanceMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1ActualDoorGapMeters = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1PartOrderValid = "loading";
    renderer.domElement.dataset.terminal4UploadedJetwayA1PartCentersMeters = "loading";
    renderer.domElement.dataset.terminal4TerminalConnectedJetwayCount = "loading";
    renderer.domElement.dataset.terminal4SourceCutoutMaterialCount = "loading";
    renderer.domElement.dataset.terminal4SourceClosedBayMaterialCount = "loading";
    renderer.domElement.dataset.terminal4SourceFacadeOpenCellCount = "loading";
    renderer.domElement.dataset.terminal4SourceFacadeClosedCellCount = "loading";
    renderer.domElement.dataset.terminal4SourceFacadeVariantMaterialCount = "loading";
    renderer.domElement.dataset.terminal4A1PortalSealAuthority = "loading";
    renderer.domElement.dataset.terminal4A1PortalSealOverlapMeters = "loading";
    renderer.domElement.dataset.terminal4A1PortalSealExactTexture = "loading";
    renderer.domElement.dataset.terminal4FacadeInfillCount = "loading";
    renderer.domElement.dataset.terminal4OpenServiceBayCount = "loading";
    renderer.domElement.dataset.terminal4JetwayDetailLevel = "loading";
    renderer.domElement.dataset.terminal4LowerFacadeFitCount = "loading";
    renderer.domElement.dataset.terminal4JetwayTextureAuthority = "loading";
    renderer.domElement.dataset.terminal4ExactJetwayTextureActive = "loading";
    renderer.domElement.dataset.groundMarkingContactMode = "loading";
    renderer.domElement.dataset.groundPavementAuthority = "loading";
    renderer.domElement.dataset.groundSourceAerialPriority = "loading";
    renderer.domElement.dataset.groundNearfieldDetailOpacity = "loading";
    const terminalLoad = installAuthoredTerminal4Visual(THREE, environment)
      .then((terminal) => {
        renderer.domElement.dataset.kphxExactLiveT4 = "ready";
        renderer.domElement.dataset.kphxExactLiveT4BuildingCount = String(environment.userData.exactLiveT4BuildingCount ?? 0);
        renderer.domElement.dataset.kphxExactLiveT4JetwayCount = String(environment.userData.exactLiveT4JetwayCount ?? 0);
        renderer.domElement.dataset.kphxExactLiveT4JetwayOpenEdgeCount = String(environment.userData.exactLiveT4JetwayOpenEdgeCount ?? 0);
        renderer.domElement.dataset.kphxExactLiveOldAirportJetwayGlbUsed = String(environment.userData.exactLiveOldAirportJetwayGlbUsed === true);
        renderer.domElement.dataset.kphxExactLiveProceduralTerminalMassing = String(environment.userData.proceduralTerminalMassing === true);
        renderer.domElement.dataset.kphxExactLiveLegacyFsxTerminal = String(environment.userData.legacyFsxTerminal === true);
        renderer.domElement.dataset.terminal4TextureCount = String(environment.userData.authoredTerminal4TextureCount);
        renderer.domElement.dataset.terminal4ExactTextureCount = String(environment.userData.authoredTerminal4ExactTextureCount);
        renderer.domElement.dataset.terminal4A1LegacyBlockRemovedTriangles = String(environment.userData.authoredTerminal4A1LegacyBlockRemovedTriangles ?? 0);
        renderer.domElement.dataset.terminal4A1LegacyBlockAuthority = environment.userData.authoredTerminal4A1LegacyBlockAuthority || "missing";
        renderer.domElement.dataset.terminal4FallbackTextureCount = String(environment.userData.authoredTerminal4FallbackTextureCount);
        renderer.domElement.dataset.terminal4TexturedMaterialCount = String(environment.userData.authoredTerminal4TexturedMaterialCount);
        renderer.domElement.dataset.terminal4Position = environment.userData.authoredTerminal4Position.map((value) => value.toFixed(3)).join(",");
        renderer.domElement.dataset.terminal4A1NearestGeometryMeters = environment.userData.authoredTerminal4A1NearestGeometryDistance.toFixed(3);
        renderer.domElement.dataset.terminal4Placement = environment.userData.authoredTerminal4Placement;
        renderer.domElement.dataset.terminal4A1JetwayWallDistance = Number.isFinite(environment.userData.authoredTerminal4A1JetwayWallDistance)
          ? environment.userData.authoredTerminal4A1JetwayWallDistance.toFixed(3)
          : "missing";
        renderer.domElement.dataset.terminal4JetwaySourceScaleAuthority = environment.userData.authoredTerminal4JetwaySourceScaleAuthority || "missing";
        renderer.domElement.dataset.terminal4JetwaySourceGeometryMode = environment.userData.authoredTerminal4JetwaySourceGeometryMode || "missing";
        renderer.domElement.dataset.terminal4RequiresOriginalJetwayMesh = String(environment.userData.authoredTerminal4RequiresOriginalJetwayMesh === true);
        renderer.domElement.dataset.terminal4JetwayInitialState = environment.userData.authoredTerminal4JetwayInitialState || "missing";
        renderer.domElement.dataset.terminal4JetwayPrePushSequence = environment.userData.authoredTerminal4JetwayRequiredPrePushSequence || "missing";
        const a1JetwayController = environment.userData.authoredTerminal4A1JetwayController || null;
        jetwayRef.current.controller = a1JetwayController;
        if (a1JetwayController?.getMotionDurationMs) {
          jetwayRef.current.transitionDurationMs = a1JetwayController.getMotionDurationMs();
        }
        a1JetwayController?.setDeployment(jetwayRef.current.target);
        renderer.domElement.dataset.a1JetwayDeployment = jetwayRef.current.deployment.toFixed(3);
        renderer.domElement.dataset.a1JetwayState = a1JetwayController?.getState?.() || "missing";
        renderer.domElement.dataset.a1JetwayAnimationAuthority = environment.userData.authoredTerminal4A1JetwayAnimationAuthority || "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayLoadState = environment.userData.authoredTerminal4UploadedJetwayLoadState || "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayCount = String(environment.userData.authoredTerminal4UploadedJetwayCount ?? "missing");
        renderer.domElement.dataset.terminal4UploadedJetwayConnectorCount = String(environment.userData.authoredTerminal4UploadedJetwayConnectorCount ?? "missing");
        renderer.domElement.dataset.terminal4UploadedJetwayVerifiedModelCount = String(environment.userData.authoredTerminal4UploadedJetwayVerifiedModelCount ?? "missing");
        renderer.domElement.dataset.terminal4UploadedJetwayReadyAuthority = environment.userData.authoredTerminal4UploadedJetwayReadyAuthority || "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayArticulationAuthority = environment.userData.authoredTerminal4UploadedJetwayArticulationAuthority || "missing";
        renderer.domElement.dataset.terminal4UploadedJetwaySourceContactDistanceMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwaySourceContactDistanceMeters) ? environment.userData.authoredTerminal4UploadedJetwaySourceContactDistanceMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayStaticArticulatedGateCount = String(environment.userData.authoredTerminal4UploadedJetwayStaticArticulatedGateCount ?? "missing");
        renderer.domElement.dataset.terminal4UploadedJetwayStaticMaximumContactErrorMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwayStaticMaximumContactErrorMeters) ? environment.userData.authoredTerminal4UploadedJetwayStaticMaximumContactErrorMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayA1TargetDoorDistanceMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwayA1TargetDoorDistanceMeters) ? environment.userData.authoredTerminal4UploadedJetwayA1TargetDoorDistanceMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayA1AttachedExtensionMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwayA1AttachedExtensionMeters) ? environment.userData.authoredTerminal4UploadedJetwayA1AttachedExtensionMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayA1PredictedDoorGapMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwayA1PredictedDoorGapMeters) ? environment.userData.authoredTerminal4UploadedJetwayA1PredictedDoorGapMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayA1PredictedContactDistanceMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwayA1PredictedContactDistanceMeters) ? environment.userData.authoredTerminal4UploadedJetwayA1PredictedContactDistanceMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayA1ActualContactDistanceMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwayA1ActualContactDistanceMeters) ? environment.userData.authoredTerminal4UploadedJetwayA1ActualContactDistanceMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayA1ActualDoorGapMeters = Number.isFinite(environment.userData.authoredTerminal4UploadedJetwayA1ActualDoorGapMeters) ? environment.userData.authoredTerminal4UploadedJetwayA1ActualDoorGapMeters.toFixed(3) : "missing";
        renderer.domElement.dataset.terminal4UploadedJetwayA1PartOrderValid = String(environment.userData.authoredTerminal4UploadedJetwayA1PartOrderValid === true);
        renderer.domElement.dataset.terminal4UploadedJetwayA1PartCentersMeters = environment.userData.authoredTerminal4UploadedJetwayA1PartCentersMeters || "missing";
        renderer.domElement.dataset.terminal4TerminalConnectedJetwayCount = String(environment.userData.authoredTerminal4TerminalConnectedJetwayCount ?? 0);
        renderer.domElement.dataset.terminal4SourceCutoutMaterialCount = String(environment.userData.authoredTerminal4SourceCutoutMaterialCount ?? 0);
        renderer.domElement.dataset.terminal4SourceClosedBayMaterialCount = String(environment.userData.authoredTerminal4SourceClosedBayMaterialCount ?? 0);
        renderer.domElement.dataset.terminal4SourceFacadeOpenCellCount = String(environment.userData.authoredTerminal4SourceFacadeOpenCellCount ?? 0);
        renderer.domElement.dataset.terminal4SourceFacadeClosedCellCount = String(environment.userData.authoredTerminal4SourceFacadeClosedCellCount ?? 0);
        renderer.domElement.dataset.terminal4SourceFacadeVariantMaterialCount = String(environment.userData.authoredTerminal4SourceFacadeVariantMaterialCount ?? 0);
        renderer.domElement.dataset.terminal4A1PortalSealAuthority = environment.userData.authoredTerminal4A1TerminalPortalSealAuthority || "missing";
        renderer.domElement.dataset.terminal4A1PortalSealOverlapMeters = String(environment.userData.authoredTerminal4A1TerminalPortalSealOverlapMeters ?? 0);
        renderer.domElement.dataset.terminal4A1PortalSealExactTexture = environment.userData.authoredTerminal4A1TerminalPortalSealExactTexture === true ? "true" : "false";
        renderer.domElement.dataset.terminal4FacadeInfillCount = String(environment.userData.authoredTerminal4FacadeInfillCount ?? 0);
        renderer.domElement.dataset.terminal4OpenServiceBayCount = String(environment.userData.authoredTerminal4OpenServiceBayCount ?? 0);
        renderer.domElement.dataset.terminal4JetwayDetailLevel = environment.userData.authoredTerminal4JetwayDetailLevel || "missing";
        renderer.domElement.dataset.terminal4LowerFacadeFitCount = String(environment.userData.authoredTerminal4LowerFacadeFitCount ?? 0);
        renderer.domElement.dataset.terminal4JetwayTextureAuthority = environment.userData.authoredTerminal4JetwayTextureAuthority || "missing";
        renderer.domElement.dataset.terminal4ExactJetwayTextureActive = String(environment.userData.authoredTerminal4ExactJetwayTextureActive === true);
        return terminal;
      })
      .catch((error) => {
        renderer.domElement.dataset.kphxExactLiveT4 = "load-error";
        renderer.domElement.dataset.terminal4A1LegacyBlockRemovedTriangles = "load-error";
        renderer.domElement.dataset.terminal4A1LegacyBlockAuthority = "load-error";
        renderer.domElement.dataset.terminal4Position = "load-error";
        renderer.domElement.dataset.terminal4A1NearestGeometryMeters = "load-error";
        renderer.domElement.dataset.terminal4Placement = "load-error";
        renderer.domElement.dataset.terminal4A1JetwayWallDistance = "load-error";
        renderer.domElement.dataset.terminal4JetwaySourceScaleAuthority = "load-error";
        renderer.domElement.dataset.terminal4JetwaySourceGeometryMode = "load-error";
        renderer.domElement.dataset.terminal4RequiresOriginalJetwayMesh = "load-error";
        renderer.domElement.dataset.terminal4JetwayInitialState = "load-error";
        renderer.domElement.dataset.terminal4JetwayPrePushSequence = "load-error";
        renderer.domElement.dataset.a1JetwayDeployment = "load-error";
        renderer.domElement.dataset.a1JetwayState = "load-error";
        renderer.domElement.dataset.a1JetwayAnimationAuthority = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayLoadState = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayCount = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayConnectorCount = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayVerifiedModelCount = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayReadyAuthority = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayArticulationAuthority = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwaySourceContactDistanceMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayStaticArticulatedGateCount = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayStaticMaximumContactErrorMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1TargetDoorDistanceMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1AttachedExtensionMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1PredictedDoorGapMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1PredictedContactDistanceMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1ActualContactDistanceMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1ActualDoorGapMeters = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1PartOrderValid = "load-error";
        renderer.domElement.dataset.terminal4UploadedJetwayA1PartCentersMeters = "load-error";
        renderer.domElement.dataset.terminal4TerminalConnectedJetwayCount = "load-error";
        renderer.domElement.dataset.terminal4SourceCutoutMaterialCount = "load-error";
        renderer.domElement.dataset.terminal4SourceClosedBayMaterialCount = "load-error";
        renderer.domElement.dataset.terminal4SourceFacadeOpenCellCount = "load-error";
        renderer.domElement.dataset.terminal4SourceFacadeClosedCellCount = "load-error";
        renderer.domElement.dataset.terminal4SourceFacadeVariantMaterialCount = "load-error";
        renderer.domElement.dataset.terminal4A1PortalSealAuthority = "load-error";
        renderer.domElement.dataset.terminal4A1PortalSealOverlapMeters = "load-error";
        renderer.domElement.dataset.terminal4A1PortalSealExactTexture = "load-error";
        renderer.domElement.dataset.terminal4FacadeInfillCount = "load-error";
        renderer.domElement.dataset.terminal4OpenServiceBayCount = "load-error";
        renderer.domElement.dataset.terminal4JetwayDetailLevel = "load-error";
        renderer.domElement.dataset.terminal4LowerFacadeFitCount = "load-error";
        renderer.domElement.dataset.terminal4JetwayTextureAuthority = "load-error";
        renderer.domElement.dataset.terminal4ExactJetwayTextureActive = "load-error";
        console.error("RampReady PHX Terminal 4 visual load failed", error);
        setMessage(`PHX Terminal 4 failed to load: ${error.message}`);
        throw error;
      });
    const surfaceLoad = Promise.all([
      installKphxPackageOwnedSurfaceLayer(THREE, environment, { strict: true, addOpaqueBaseUnderlay: false }),
      installKphxPackageOwnedSurfaceLayer(THREE, environment, {
        strict: true,
        manifestUrl: "/models/kphx-full-airport/t4-a1-zdp-surfaces/manifest.json",
        networkUrl: "/models/kphx-full-airport/t4-a1-zdp-surfaces/surface-network.json",
        loadPolygons: true,
        loadDrapedOrthophotos: false,
        loadLines: false,
        addOpaqueBaseUnderlay: false,
      }),
    ])
      .then(([packageResult, a1ZdpResult]) => {
        const packageData = packageResult.layer.userData;
        const zdpData = a1ZdpResult.layer.userData;

        const exactConcreteSourceResource = "ZDP_Library/ground_textures/concrete/flat/Flat_New_Uniform.pol";
        const exactConcreteSourceMesh = a1ZdpResult.layer.children.find(
          (child) => child?.userData?.sourceResource === exactConcreteSourceResource && child.material,
        );
        const invisibleConcreteResources = new Set([
          "GroundPolys/invis_concrete.pol",
          "Ground_Textures/Invisible_Concrete.pol",
        ]);
        let transparentConcreteUnderlayCount = 0;
        if (exactConcreteSourceMesh?.material) {
          for (const child of packageResult.layer.children) {
            if (!child?.isMesh || !invisibleConcreteResources.has(child.userData?.sourceResource)) continue;
            // X-Plane invisible-concrete helpers carry placement/surface semantics but are not visible scenery.
            // Preserve their exact authored footprint for the compatibility underlay, then hide the helper itself.
            child.visible = false;
            child.userData.kphxInvisibleConcreteSourceHidden = true;
            const geometry = child.geometry.clone();
            geometry.translate(0, -0.015, 0);
            const material = exactConcreteSourceMesh.material.clone();
            material.name = "KPHX_INVISIBLE_CONCRETE_SOURCE_UNDERLAY";
            material.transparent = false;
            material.opacity = 1;
            material.alphaTest = 0;
            material.depthWrite = true;
            material.side = THREE.DoubleSide;
            const underlay = new THREE.Mesh(geometry, material);
            underlay.name = `KPHX_INVISIBLE_CONCRETE_UNDERLAY_${child.userData?.wedObjectId || transparentConcreteUnderlayCount}`;
            underlay.renderOrder = (child.renderOrder || 0) - 0.5;
            underlay.receiveShadow = true;
            underlay.userData = {
              kphxFullAirport: true,
              kphxSurface: true,
              kphxTransparentConcreteCompatibilityUnderlay: true,
              sourceHelperResource: child.userData?.sourceResource,
              sourceConcreteResource: exactConcreteSourceResource,
            };
            environment.add(underlay);
            transparentConcreteUnderlayCount += 1;
          }
        }
        renderer.domElement.dataset.kphxTransparentConcreteUnderlayCount = String(transparentConcreteUnderlayCount);

        const failures = [
          ...(packageData.failures || []),
          ...(zdpData.failures || []),
        ];
        const ready = packageData.ready === true && zdpData.ready === true && failures.length === 0;
        renderer.domElement.dataset.groundSource = "KPHX 1.75.1 exact WED package + A1 ZDP pavement";
        renderer.domElement.dataset.kphxVersion = String(packageData.sourceVersion || zdpData.sourceVersion || "missing");
        renderer.domElement.dataset.kphxSurfaceReady = String(ready);
        renderer.domElement.dataset.kphxSurfacePolygonCount = String((packageData.polygonCount ?? 0) + (zdpData.polygonCount ?? 0));
        renderer.domElement.dataset.kphxSurfaceOrthophotoCount = String((packageData.drapedOrthophotoCount ?? 0) + (zdpData.drapedOrthophotoCount ?? 0));
        renderer.domElement.dataset.kphxSurfaceLineMeshCount = String((packageData.lineMeshCount ?? 0) + (zdpData.lineMeshCount ?? 0));
        renderer.domElement.dataset.kphxSurfaceMaterialCount = String((packageData.materialCount ?? 0) + (zdpData.materialCount ?? 0));
        renderer.domElement.dataset.kphxSurfaceFailureCount = String(failures.length);
        renderer.domElement.dataset.kphxA1ZdpSurfaceReady = String(zdpData.ready === true);
        renderer.domElement.dataset.kphxA1ZdpSurfacePolygonCount = String(zdpData.polygonCount ?? 0);
        renderer.domElement.dataset.kphxA1ZdpOpaqueBaseUnderlayCount = String(zdpData.opaqueBaseUnderlayCount ?? 0);
        renderer.domElement.dataset.kphxA1ZdpSurfaceOrthophotoCount = String(zdpData.drapedOrthophotoCount ?? 0);
        renderer.domElement.dataset.kphxA1ZdpSurfaceLineMeshCount = String(zdpData.lineMeshCount ?? 0);
        renderer.domElement.dataset.photoGroundSource = "not-used-exact-kphx-1.75.1-only";
        return { packageResult, a1ZdpResult, ready, failures };
      })
      .catch((error) => {
        renderer.domElement.dataset.groundSource = "load-error";
        renderer.domElement.dataset.kphxSurfaceReady = "false";
        renderer.domElement.dataset.kphxA1ZdpSurfaceReady = "false";
        renderer.domElement.dataset.kphxSurfaceFailureCount = "load-error";
        renderer.domElement.dataset.photoGroundSource = "not-used-exact-kphx-1.75.1-only";
        console.error("RampReady exact KPHX surface load failed", error);
        setMessage(`Exact PHX surface layer failed to load: ${error.message}`);
        throw error;
      });

    const a1MarkingsLoad = installKphxPackageOwnedSurfaceLayer(THREE, environment, {
      strict: true,
      manifestUrl: "/models/kphx-full-airport/t4-a1-zdp-surfaces/manifest.json",
      networkUrl: "/models/kphx-full-airport/t4-a1-zdp-surfaces/surface-network.json",
      loadPolygons: false,
      loadDrapedOrthophotos: false,
      loadLines: true,
    })
      .then((result) => {
        const data = result.layer.userData;
        renderer.domElement.dataset.kphxA1ZdpMarkingsReady = String(data.ready === true);
        renderer.domElement.dataset.kphxA1ZdpMarkingLineMeshCount = String(data.lineMeshCount ?? 0);
        renderer.domElement.dataset.kphxA1ZdpMarkingTextureDecodeCount = String(data.uniqueTextureDecodeCount ?? 0);
        renderer.domElement.dataset.kphxA1ZdpMarkingFailureCount = String((data.failures || []).length);
        renderer.domElement.dataset.groundSource = "KPHX 1.75.1 exact WED package + A1 ZDP pavement + markings";
        return result;
      })
      .catch((error) => {
        renderer.domElement.dataset.kphxA1ZdpMarkingsReady = "load-error";
        renderer.domElement.dataset.kphxA1ZdpMarkingFailureCount = "load-error";
        console.error("RampReady exact A1 ZDP markings load failed", error);
        setMessage(`Exact A1 ramp markings failed to load: ${error.message}`);
        throw error;
      });

    void Promise.all([terminalLoad, surfaceLoad, a1MarkingsLoad])
      .then(([, surfaceState]) => {
        const baseResource = "ZDP_Library/ground_textures/concrete/flat/Flat_New_Uniform.pol";
        const sourceMesh = surfaceState.a1ZdpResult.layer.children.find((child) => child?.userData?.sourceResource === baseResource && child.material?.map);
        if (!sourceMesh) throw new Error("Exact T4 base apron source texture mesh is missing");

        const t4Bounds = new THREE.Box3();
        const terminalObject = environment.userData.authoredTerminal4;
        const jetwayObject = environment.userData.authoredTerminal4Jetways;
        if (terminalObject) t4Bounds.expandByObject(terminalObject);
        if (jetwayObject) t4Bounds.expandByObject(jetwayObject);
        if (t4Bounds.isEmpty()) throw new Error("Exact T4 apron bounds are unavailable");

        const apronMargin = 90;
        const apronWidth = Math.max(1, (t4Bounds.max.x - t4Bounds.min.x) + apronMargin * 2);
        const apronDepth = Math.max(1, (t4Bounds.max.z - t4Bounds.min.z) + apronMargin * 2);
        const apronCenterX = (t4Bounds.min.x + t4Bounds.max.x) * 0.5;
        const apronCenterZ = (t4Bounds.min.z + t4Bounds.max.z) * 0.5;

        const apronMap = sourceMesh.material.map.clone();
        apronMap.wrapS = THREE.RepeatWrapping;
        apronMap.wrapT = THREE.RepeatWrapping;
        apronMap.repeat.set(apronWidth / 36, apronDepth / 36);
        apronMap.needsUpdate = true;

        const apronNormalMap = sourceMesh.material.normalMap?.clone?.() || null;
        if (apronNormalMap) {
          apronNormalMap.wrapS = THREE.RepeatWrapping;
          apronNormalMap.wrapT = THREE.RepeatWrapping;
          apronNormalMap.repeat.set(apronWidth / 36, apronDepth / 36);
          apronNormalMap.needsUpdate = true;
        }

        const apronMaterial = new THREE.MeshStandardMaterial({
          map: apronMap,
          normalMap: apronNormalMap,
          roughness: sourceMesh.material.roughness ?? 0.88,
          metalness: sourceMesh.material.metalness ?? 0,
          transparent: false,
          opacity: 1,
          alphaTest: 0,
          side: THREE.DoubleSide,
          depthWrite: true,
        });
        if (apronNormalMap && sourceMesh.material.normalScale) {
          apronMaterial.normalScale.copy(sourceMesh.material.normalScale);
        }
        apronMaterial.name = "KPHX_T4_EXACT_SOURCE_TEXTURE_BASE_APRON";

        const apronGeometry = new THREE.PlaneGeometry(apronWidth, apronDepth, 1, 1);
        apronGeometry.rotateX(-Math.PI / 2);
        const apronMesh = new THREE.Mesh(apronGeometry, apronMaterial);
        apronMesh.name = "KPHX_T4_BASE_APRON_COMPATIBILITY_UNDERLAY";
        apronMesh.position.set(apronCenterX, -0.06, apronCenterZ);
        apronMesh.renderOrder = -100;
        apronMesh.receiveShadow = true;
        apronMesh.userData = {
          kphxBaseApronCompatibility: true,
          sourceResource: baseResource,
          sourceTextureSha256: "4feecd5f339821c3eecd6d9423faf5bd333886d3c57db539cbd487483aafb70b",
          textureScaleMeters: 36,
          placementAuthority: "derived from exact T4 building + jetway bounds; visual base only",
          collisionAuthority: "none",
        };
        environment.add(apronMesh);
        renderer.domElement.dataset.kphxT4BaseApronReady = "true";
        renderer.domElement.dataset.kphxT4BaseApronSource = baseResource;
        renderer.domElement.dataset.kphxT4BaseApronWidthMeters = apronWidth.toFixed(3);
        renderer.domElement.dataset.kphxT4BaseApronDepthMeters = apronDepth.toFixed(3);

        airportCollision.staticTargets = [
          environment.userData.authoredTerminal4,
          environment.userData.authoredTerminal4Jetways,
        ].filter((target) => target?.isObject3D);
        airportCollision.aircraftTarget = aircraft;
        airportCollision.ready = airportCollision.staticTargets.length === 2;
        renderer.domElement.dataset.airportCollisionReady = airportCollision.ready ? "true" : "false";
        renderer.domElement.dataset.airportCollisionTargetCount = String(airportCollision.staticTargets.length);
        renderer.domElement.dataset.terminal4A1RetractionAuthority =
          environment.userData.authoredTerminal4A1JetwayAnimationAuthority || "missing";
        renderer.domElement.dataset.terminal4A1RetractionClearanceMeters =
          Number(environment.userData.authoredTerminal4A1JetwayAttachedLatMeters).toFixed(3);
        renderer.domElement.dataset.terminal4A1RetractionRatio = "1.000000";
        renderer.domElement.dataset.terminal4A1NativeRetractionActive =
          environment.userData.authoredTerminal4A1JetwayController ? "true" : "false";
        renderer.domElement.dataset.terminal4A1MotionDurationMs =
          String(environment.userData.authoredTerminal4A1JetwayMotionDurationMs ?? "missing");
        renderer.domElement.dataset.terminal4A1VerticalResolved =
          String(environment.userData.authoredTerminal4A1JetwayVerticalResolved === true);
        renderer.domElement.dataset.environmentSource = environment.userData.environmentSource;
      })
      .catch(() => {
        renderer.domElement.dataset.environmentSource = "load-error";
      });

    const camera = new THREE.PerspectiveCamera(58, 1, 0.1, 8000);
    const rig = createProceduralLektroRig(THREE, equipmentId);
    rig.root.position.set(A1_EQUIPMENT_SPAWN.x, 0, A1_EQUIPMENT_SPAWN.z);
    rig.root.rotation.y = A1_EQUIPMENT_SPAWN.yaw;
    rig.root.userData.equipmentId = equipmentId;
    renderer.domElement.dataset.tugSource = equipmentId === "standup-tug"
      ? "loading"
      : equipmentId === "manager-kubota"
        ? "loading"
        : "procedural-lektro";
    renderer.domElement.dataset.steeringMode = rig.profile.steeringMode;
    renderer.domElement.dataset.rigProfile = rig.profile.id;
    renderer.domElement.dataset.rigWheelbaseMeters = String(rig.profile.wheelbase);
    renderer.domElement.dataset.rigTurningRadiusMeters = String(rig.profile.turningRadius ?? "");
    renderer.domElement.dataset.rigFreeMaxSpeedMps = String(rig.profile.freeMaxSpeed ?? "");
    renderer.domElement.dataset.rigTowMaxSpeedMps = String(rig.profile.towMaxSpeed ?? "");
    renderer.domElement.dataset.rigKinematicMaxSteerDegrees = Number.isFinite(rig.profile.kinematicMaxSteerAngle)
      ? THREE.MathUtils.radToDeg(rig.profile.kinematicMaxSteerAngle).toFixed(3)
      : "";
    renderer.domElement.dataset.rigVisualMaxSteerDegrees = Number.isFinite(rig.profile.visualMaxSteerAngle)
      ? THREE.MathUtils.radToDeg(rig.profile.visualMaxSteerAngle).toFixed(3)
      : "";
    renderer.domElement.dataset.operatorSide = rig.profile.operatorEye[0] > 0 ? "right" : "left";
    renderer.domElement.dataset.operatorControls = equipmentId === "standup-tug" ? "loading" : "not-applicable";
    void installRuntimeEquipmentVisual(rig, equipmentId)
      .then((source) => {
        renderer.domElement.dataset.tugSource = source;
        renderer.domElement.dataset.tugModelForwardCorrectionDegrees = String(rig.root.userData.modelForwardCorrectionDegrees ?? 0);
        if (equipmentId === "lektro-88") {
          renderer.domElement.dataset.lektroAuthoredRearSteerBinding = String(rig.root.userData.authoredRearSteerBinding ?? "missing");
          renderer.domElement.dataset.lektroAuthoredRearSteerMode = String(rig.root.userData.authoredRearSteerMode ?? "missing");
        }
        if (equipmentId === "standup-tug") {
          renderer.domElement.dataset.operatorControls = rig.root.userData.standupSteeringWheel && rig.root.userData.standupBatteryGauge ? "ready" : "missing";
        }
      })
      .catch((error) => {
        renderer.domElement.dataset.tugSource = "load-error";
        renderer.domElement.dataset.operatorControls = "load-error";
        console.error("RampReady equipment visual load failed", error);
        setMessage(`Equipment model failed to load: ${error.message}`);
      });
    const rigFailures = validateTugRig(rig);
    if (rigFailures.length) throw new Error(`Invalid tug rig: ${rigFailures.join(", ")}`);
    const aircraft = buildCRJ700Aircraft(THREE, material, cylinder);
    aircraft.position.set(A1_AIRCRAFT_START_X, 0, NOSE_START_Z);
    aircraft.rotation.y = A1_AIRCRAFT_YAW_RADIANS;
    aircraft.scale.setScalar(0.82);
    scene.add(rig.root, aircraft);

    const sim = { renderer, scene, camera, environment, rig, aircraft, connection: createConnectionState(), dynamics: createA1SpawnPushbackState(), last: performance.now(), lastHud: 0 };
    simRef.current = sim;

    const canvas = renderer.domElement;
    canvas.dataset.a1AircraftHeadingReady = "true";
    canvas.dataset.a1AircraftHeadingAuthority = A1_AIRCRAFT_HEADING_AUTHORITY;
    canvas.dataset.a1AircraftSourceHeadingDegrees = A1_SOURCE_HEADING_DEGREES.toFixed(2);
    canvas.dataset.a1AircraftRuntimeYawRadians = A1_AIRCRAFT_YAW_RADIANS.toFixed(6);
    canvas.dataset.a1AircraftRuntimeYawDegrees = THREE.MathUtils.radToDeg(A1_AIRCRAFT_YAW_RADIANS).toFixed(2);
    canvas.dataset.a1AircraftModelForwardAxis = "-Z";
    canvas.dataset.kphxT4SupportedRampPositionCount = String(KPHX_T4_GATE_POSE_SOURCE.supportedRampPositionCount);
    canvas.dataset.kphxT4SupportedGateNameCount = String(KPHX_T4_GATE_POSE_SOURCE.supportedGateNameCount);
    canvas.dataset.a1EquipmentSpawnAuthority = A1_EQUIPMENT_SPAWN_AUTHORITY;
    canvas.dataset.a1EquipmentSpawnX = A1_EQUIPMENT_SPAWN.x.toFixed(6);
    canvas.dataset.a1EquipmentSpawnZ = A1_EQUIPMENT_SPAWN.z.toFixed(6);
    canvas.dataset.a1EquipmentSpawnYawDegrees = THREE.MathUtils.radToDeg(A1_EQUIPMENT_SPAWN.yaw).toFixed(2);
    canvas.dataset.a1EquipmentApproachOffsetMeters = A1_EQUIPMENT_APPROACH_OFFSET_METERS.toFixed(3);
    const syncCameraDataset = () => {
      canvas.dataset.cameraYaw = orbitRef.current.yaw.toFixed(4);
      canvas.dataset.cameraPitch = orbitRef.current.pitch.toFixed(4);
      canvas.dataset.cameraDistance = orbitRef.current.distance.toFixed(3);
    };
    const handlePointerDown = (event) => {
      if (cameraRef.current !== "chase") return;
      if (event.pointerType === "mouse" && event.button !== 0) return;
      orbitRef.current.pointerId = event.pointerId;
      orbitRef.current.lastX = event.clientX;
      orbitRef.current.lastY = event.clientY;
      canvas.setPointerCapture?.(event.pointerId);
      event.preventDefault();
    };
    const handlePointerMove = (event) => {
      if (orbitRef.current.pointerId !== event.pointerId || cameraRef.current !== "chase") return;
      const dx = event.clientX - orbitRef.current.lastX;
      const dy = event.clientY - orbitRef.current.lastY;
      orbitRef.current.lastX = event.clientX;
      orbitRef.current.lastY = event.clientY;
      orbitRef.current.yaw -= dx * 0.006;
      orbitRef.current.pitch = clamp(orbitRef.current.pitch + dy * 0.0045, 0.08, 1.18);
      syncCameraDataset();
      event.preventDefault();
    };
    const handlePointerUp = (event) => {
      if (orbitRef.current.pointerId !== event.pointerId) return;
      orbitRef.current.pointerId = null;
      canvas.releasePointerCapture?.(event.pointerId);
    };
    const handleWheel = (event) => {
      if (cameraRef.current !== "chase") return;
      orbitRef.current.distance = clamp(orbitRef.current.distance + event.deltaY * 0.012, 7, 34);
      syncCameraDataset();
      event.preventDefault();
    };
    canvas.addEventListener("pointerdown", handlePointerDown);
    window.addEventListener("pointermove", handlePointerMove, { passive: false });
    window.addEventListener("pointerup", handlePointerUp);
    window.addEventListener("pointercancel", handlePointerUp);
    canvas.addEventListener("wheel", handleWheel, { passive: false });

    const resize = () => {
      const width = Math.max(1, mount.clientWidth || window.innerWidth);
      const height = Math.max(1, mount.clientHeight || window.innerHeight);
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
      renderer.setSize(width, height, false);
    };
    resize();
    window.addEventListener("resize", resize);

    const cameraTarget = new THREE.Vector3();
    const desiredCamera = new THREE.Vector3();
    let frame = 0;
    const tick = (now) => {
      const rawFrameDt = Math.max(0.001, (now - sim.last) / 1000);
      const dt = Math.min(0.04, rawFrameDt);
      sim.last = now;
      const inspectionActive = inspectionRef.current;
      const jetway = jetwayRef.current;
      if (jetway.controller) {
        const difference = jetway.target - jetway.deployment;
        if (Math.abs(difference) > 0.0005) {
          if (!(jetway.transitionStartedAt > 0)) {
            jetway.transitionStartDeployment = jetway.deployment;
            jetway.transitionStartedAt = now;
          }
          const transitionElapsedMs = Math.max(0, now - jetway.transitionStartedAt);
          const transitionDistance = Math.max(0.001, Math.abs(jetway.target - jetway.transitionStartDeployment));
          const transitionDurationMs = Math.max(900, jetway.transitionDurationMs * transitionDistance);
          const transitionProgress = Math.min(1, transitionElapsedMs / transitionDurationMs);
          // Marginal AutoGate DISENGAGE uses a linear elapsed-time ratio over 15 seconds.
          jetway.deployment = jetway.transitionStartDeployment
            + (jetway.target - jetway.transitionStartDeployment) * transitionProgress;
          if (transitionProgress >= 1) {
            jetway.deployment = jetway.target;
            jetway.transitionStartDeployment = jetway.target;
            jetway.transitionStartedAt = 0;
          }
          jetway.controller.setDeployment(jetway.deployment);
        }
        renderer.domElement.dataset.a1JetwayDeployment = jetway.deployment.toFixed(3);
        const currentA1JetwayState = jetway.controller.getState?.() || "unknown";
        renderer.domElement.dataset.a1JetwayState = currentA1JetwayState;
        renderer.domElement.dataset.a1JetwayStateHistory = jetway.controller.getStateHistory?.().join(",") || currentA1JetwayState;
        renderer.domElement.dataset.a1JetwayLatMeters = Number(jetway.controller.getLatMeters?.() ?? Number.NaN).toFixed(3);
        renderer.domElement.dataset.a1JetwayRetractedMeters = Number(jetway.controller.getRetractedMeters?.() ?? Number.NaN).toFixed(3);
        renderer.domElement.dataset.a1JetwayBridgeYawDeltaDegrees = Number(jetway.controller.getBridgeYawDeltaDegrees?.() ?? Number.NaN).toFixed(3);
        renderer.domElement.dataset.a1JetwayCabinCounterYawDeltaDegrees = Number(jetway.controller.getCabinCounterYawDeltaDegrees?.() ?? Number.NaN).toFixed(3);
        if (!inspectionActive && jetway.retractionRequested && jetway.deployment <= 0.005 && stageRef.current === 0) {
          jetway.retractionRequested = false;
          stageRef.current = 1;
          setStage(1);
          setMessage("Jetway parked clear. Approach directly from the front and stop inside the capture envelope.");
        }
      }
      const before = connectionMetrics(sim);
      const clearDistance = Math.hypot(rig.root.position.x - aircraft.position.x, rig.root.position.z - aircraft.position.z);
      if (inspectionActive) {
        if (sim.connection.phase !== CONNECTION_PHASES.APPROACH) sim.connection = createConnectionState();
      } else {
        sim.connection = stepConnection(sim.connection, { metrics: before, speed: sim.dynamics.speed, clearDistance }, dt);
      }

      if (!inspectionActive && stageRef.current === 2 && sim.connection.phase === CONNECTION_PHASES.SECURED) {
        sim.dynamics = createPushbackState({
          tugX: rig.root.position.x,
          tugZ: rig.root.position.z,
          tugYaw: rig.root.rotation.y,
          aircraftX: aircraft.position.x,
          aircraftZ: aircraft.position.z,
          aircraftYaw: aircraft.rotation.y,
        });
        stageRef.current = 3;
        setStage(3);
        setMessage("Nose gear lifted and secured. Request pushback clearance.");
      }
      if (!inspectionActive && stageRef.current === 6 && sim.connection.phase === CONNECTION_PHASES.RELEASED) {
        stageRef.current = 7;
        setStage(7);
        setMessage("Nose gear released. Select REV and drive at least 2.2 m clear.");
      }
      if (!inspectionActive && stageRef.current === 7 && sim.connection.phase === CONNECTION_PHASES.CLEAR) {
        driveRef.current.throttle = 0;
        setThrottle(0);
        stageRef.current = 8;
        setStage(8);
        setMessage(`Tug clear. Scenario complete. Score ${Math.round(scoreRef.current)}/100.`);
      }

      const drive = driveRef.current;
      let steer = drive.steer;
      if (keysRef.current.has("a") || keysRef.current.has("arrowleft")) steer += 1;
      if (keysRef.current.has("d") || keysRef.current.has("arrowright")) steer -= 1;
      const motionAllowed = inspectionActive || (connectionAllowsMotion(sim.connection) && ![3, 4, 8].includes(stageRef.current));
      const towing = !inspectionActive && sim.connection.phase === CONNECTION_PHASES.TOWING;
      const keyboardForward = inspectionActive && (keysRef.current.has("w") || keysRef.current.has("arrowup"));
      const keyboardReverse = inspectionActive && (keysRef.current.has("s") || keysRef.current.has("arrowdown"));
      const inspectionDirection = keyboardReverse ? -1 : keyboardForward ? 1 : drive.direction;
      const inspectionThrottle = keyboardForward || keyboardReverse ? Math.max(drive.throttle, 1) : drive.throttle;
      const dynamicsCommand = {
        connected: towing,
        throttle: motionAllowed && (!towing || inspectionDirection === 1) ? inspectionThrottle : 0,
        direction: inspectionDirection,
        steer: clamp(steer, -1, 1),
        brake: drive.brake || keysRef.current.has(" ") || !motionAllowed,
        cradleOffset: rig.profile.cradleOffset,
        steeringMode: rig.profile.steeringMode,
        wheelbase: rig.profile.wheelbase,
        freeMaxSpeed: rig.profile.freeMaxSpeed,
        towMaxSpeed: rig.profile.towMaxSpeed,
        maxSteerAngle: rig.profile.kinematicMaxSteerAngle,
      };
      if (inspectionActive) {
        let remainingInspectionDt = Math.min(0.5, rawFrameDt);
        while (remainingInspectionDt > 0.000001) {
          const inspectionStepDt = Math.min(0.04, remainingInspectionDt);
          sim.dynamics = stepPushbackDynamics(sim.dynamics, dynamicsCommand, inspectionStepDt);
          remainingInspectionDt -= inspectionStepDt;
        }
      } else {
        sim.dynamics = stepPushbackDynamics(sim.dynamics, dynamicsCommand, dt);
      }

      const state = sim.dynamics;
      const previousTug = { x: rig.root.position.x, z: rig.root.position.z, yaw: rig.root.rotation.y };
      const tugBlocked = airportMovementBlocked({
        startX: previousTug.x,
        startZ: previousTug.z,
        endX: state.tugX,
        endZ: state.tugZ,
        radius: equipmentId === "standup-tug" ? 0.92 : 1.18,
        heights: equipmentId === "standup-tug" ? [0.48, 1.15, 1.9] : [0.42, 0.92, 1.55],
        includeAircraft: inspectionActive,
      });
      let aircraftBlocked = false;
      if (connectionHasAircraft(sim.connection)) {
        const previousSamples = aircraftCollisionSamples(aircraft.position.x, aircraft.position.z, aircraft.rotation.y);
        const nextSamples = aircraftCollisionSamples(state.aircraftX, state.aircraftZ, state.aircraftYaw);
        aircraftBlocked = previousSamples.some((sample, index) => airportMovementBlocked({
          startX: sample.x,
          startZ: sample.z,
          endX: nextSamples[index].x,
          endZ: nextSamples[index].z,
          radius: index >= 4 ? 1.35 : 1.05,
          heights: index >= 4 ? [1.1, 2.2, 3.5] : [0.72, 2.05, 3.8],
        }));
      }
      const collisionBlocked = tugBlocked || aircraftBlocked;
      if (collisionBlocked) {
        state.tugX = previousTug.x;
        state.tugZ = previousTug.z;
        state.tugYaw = previousTug.yaw;
        if (connectionHasAircraft(sim.connection)) {
          state.aircraftX = aircraft.position.x;
          state.aircraftZ = aircraft.position.z;
          state.aircraftYaw = aircraft.rotation.y;
        }
        state.speed = 0;
        if (!airportCollision.blocked) airportCollision.count += 1;
        if (now - airportCollision.lastMessageAt > 1200) {
          airportCollision.lastMessageAt = now;
          setMessage(inspectionActive
            ? "Collision prevented. Stop, steer clear, and continue the airport inspection."
            : "Collision prevented. Stop and correct the pushback path before continuing.");
        }
      }
      airportCollision.blocked = collisionBlocked;
      renderer.domElement.dataset.airportCollisionState = collisionBlocked ? "blocked" : "clear";
      renderer.domElement.dataset.airportCollisionCount = String(airportCollision.count);
      rig.root.position.set(state.tugX, 0, state.tugZ);
      rig.root.rotation.y = state.tugYaw;
      rig.setSteering(state.steerAngle || 0);
      if (equipmentId === "lektro-88") {
        const authoredRearSteerRadians = Number(rig.root.userData.authoredRearSteerRadians ?? 0);
        renderer.domElement.dataset.lektroAuthoredRearSteerRadians = authoredRearSteerRadians.toFixed(6);
        renderer.domElement.dataset.lektroAuthoredRearSteerDegrees = THREE.MathUtils.radToDeg(authoredRearSteerRadians).toFixed(3);
      }
      const visualMotionDt = inspectionActive ? Math.min(0.5, rawFrameDt) : dt;
      rig.rotateWheels(state.speed * visualMotionDt);
      if (connectionHasAircraft(sim.connection)) {
        aircraft.position.set(state.aircraftX, 0, state.aircraftZ);
        aircraft.rotation.y = state.aircraftYaw;
      }
      const lift = sim.connection.phase === CONNECTION_PHASES.CAPTURING
        ? sim.connection.progress
        : sim.connection.phase === CONNECTION_PHASES.LOWERING
          ? 1 - sim.connection.progress
          : connectionHasAircraft(sim.connection) ? 1 : 0;
      rig.setLiftProgress(lift);

      const metrics = connectionMetrics(sim);
      const stopRemaining = STOP_Z - state.aircraftZ;
      if (towing && state.jackknifeWarning) setMessage("Articulation limit approaching. Reduce power and steer toward alignment.");
      if (towing && (Math.abs(state.speed) > 1.05 || Math.abs(state.aircraftX) > 1.8)) scoreRef.current = Math.max(0, scoreRef.current - 0.02);
      if (towing && state.aircraftZ >= STOP_Z - 0.5) {
        const hard = Math.abs(state.speed) >= 0.18;
        if (hard) scoreRef.current = Math.max(0, scoreRef.current - 10);
        sim.dynamics.speed = 0;
        driveRef.current.throttle = 0;
        setThrottle(0);
        stageRef.current = 6;
        setStage(6);
        setMessage(hard ? "Stopped too hard. Straighten, then lower." : "Good stop. Straighten, then lower.");
      }

      const target = inspectionActive ? rig.root.position : connectionHasAircraft(sim.connection) ? aircraft.position : rig.root.position;
      if (cameraRef.current === "driver") {
        const operatorEyeWorld = rig.getOperatorEyeWorld(new THREE.Vector3());
        const operatorLookWorld = rig.getOperatorLookWorld(new THREE.Vector3());
        // Operator view is a seated viewpoint, not a cinematic transition.
        // Snap to the calibrated driver-eye anchor so low mobile frame rates cannot
        // leave the camera stranded between chase view and the operator station.
        camera.position.copy(operatorEyeWorld);
        camera.lookAt(operatorLookWorld);
        if (equipmentId === "lektro-88") {
          canvas.dataset.lektroOperatorEyeLocalX = rig.profile.operatorEye[0].toFixed(3);
          canvas.dataset.lektroOperatorEyeLocalY = rig.profile.operatorEye[1].toFixed(3);
          canvas.dataset.lektroOperatorEyeLocalZ = rig.profile.operatorEye[2].toFixed(3);
          canvas.dataset.lektroOperatorEyeWorldX = operatorEyeWorld.x.toFixed(6);
          canvas.dataset.lektroOperatorEyeWorldY = operatorEyeWorld.y.toFixed(6);
          canvas.dataset.lektroOperatorEyeWorldZ = operatorEyeWorld.z.toFixed(6);
          canvas.dataset.lektroOperatorCameraX = camera.position.x.toFixed(6);
          canvas.dataset.lektroOperatorCameraY = camera.position.y.toFixed(6);
          canvas.dataset.lektroOperatorCameraZ = camera.position.z.toFixed(6);
          canvas.dataset.lektroOperatorViewAuthority = "r187a-driver-seat-after-180deg-model-forward-correction";
        }
      } else if (cameraRef.current === "overhead") {
        camera.position.lerp(new THREE.Vector3(target.x, 34, target.z + 2), 0.16);
        camera.lookAt(target.x, 0, target.z + 5);
      } else {
        const inspectionPresetConfig = inspectionActive
          ? INSPECTION_PRESETS[inspectionPresetRef.current]
          : null;
        if (inspectionPresetConfig?.cameraPosition && inspectionPresetConfig?.cameraTarget) {
          desiredCamera.fromArray(inspectionPresetConfig.cameraPosition);
          cameraTarget.fromArray(inspectionPresetConfig.cameraTarget);
          camera.position.lerp(desiredCamera, 0.16);
          camera.lookAt(cameraTarget);
        } else {
          const orbit = orbitRef.current;
          cameraTarget.set(target.x, 1.3, target.z + (connectionHasAircraft(sim.connection) ? 0 : 2.5));
          const horizontal = Math.cos(orbit.pitch) * orbit.distance;
          desiredCamera.set(
            cameraTarget.x + Math.sin(orbit.yaw) * horizontal,
            cameraTarget.y + Math.sin(orbit.pitch) * orbit.distance,
            cameraTarget.z + Math.cos(orbit.yaw) * horizontal,
          );
          camera.position.lerp(desiredCamera, 0.16);
          camera.lookAt(cameraTarget);
        }
      }

      const aircraftSource = aircraft.userData.renderedAircraftSource || aircraft.userData.aircraftAssetCandidateId || aircraft.userData.aircraftAssetState || "loading";
      canvas.dataset.aircraftSource = aircraftSource;
      canvas.dataset.inspectionTugX = rig.root.position.x.toFixed(3);
      canvas.dataset.inspectionTugZ = rig.root.position.z.toFixed(3);
      canvas.dataset.inspectionSpeed = Math.abs(state.speed).toFixed(3);
      canvas.dataset.inspectionTimeIntegration = inspectionActive ? "elapsed-substep-40ms" : "training-frame-capped";
      if (now - sim.lastHud > 100) {
        sim.lastHud = now;
        setHud({
          speed: Math.abs(state.speed),
          stop: stopRemaining,
          capture: metrics.distance,
          ready: sim.connection.phase === CONNECTION_PHASES.ALIGNED,
          articulation: Math.abs(THREE.MathUtils.radToDeg(state.articulation)),
          warning: Math.abs(state.articulation) >= JACKKNIFE_WARNING,
          score: Math.round(scoreRef.current),
          phase: inspectionActive ? "inspection" : sim.connection.phase,
          progress: sim.connection.progress,
          tug: equipmentId,
          aircraft: aircraftSource,
        });
      }
      renderer.render(scene, camera);
      frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);

    return () => {
      cancelAnimationFrame(frame);
      window.removeEventListener("resize", resize);
      canvas.removeEventListener("pointerdown", handlePointerDown);
      window.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("pointerup", handlePointerUp);
      window.removeEventListener("pointercancel", handlePointerUp);
      canvas.removeEventListener("wheel", handleWheel);
      dispose(scene);
      renderer.dispose();
      simRef.current = null;
    };
  }, [equipmentId]);

  useEffect(() => {
    const down = (event) => keysRef.current.add(event.key.toLowerCase());
    const up = (event) => keysRef.current.delete(event.key.toLowerCase());
    window.addEventListener("keydown", down);
    window.addEventListener("keyup", up);
    return () => {
      window.removeEventListener("keydown", down);
      window.removeEventListener("keyup", up);
    };
  }, []);

  const releaseSteer = () => { driveRef.current.steer = 0; };
  const releaseBrake = () => { driveRef.current.brake = false; };

  return <div className="rr-shell" data-equipment-id={equipmentId} data-inspection-mode={inspectionMode ? "active" : "training"} data-inspection-preset={inspectionMode ? inspectionPreset : "training"}>
    <div ref={mountRef} className="rr-scene" />
    <section className="rr-hud">
      <div className="rr-topline">
        <div>
          <div className="rr-kicker">{inspectionMode ? "Free drive" : `Step ${stage + 1} / ${STAGES.length}`}</div>
          <h1>{inspectionMode ? "Airport inspection mode" : STAGES[stage]}</h1>
        </div>
        <div className="rr-top-tools">
          <button
            className="rr-inspection-toggle"
            type="button"
            aria-pressed={inspectionMode}
            onClick={toggleInspectionDrive}
          >{inspectionMode ? "Return to training" : "Free-drive inspection"}</button>
          {inspectionMode && <select
            className="rr-view-select rr-inspection-location"
            value={inspectionPreset}
            onChange={(event) => moveInspectionToPreset(event.target.value)}
            aria-label="Inspection location"
          >
            {Object.values(INSPECTION_PRESETS).map((preset) => <option key={preset.id} value={preset.id}>{preset.label}</option>)}
          </select>}
          <select className="rr-view-select" value={cameraMode} onChange={(event) => setCameraMode(event.target.value)} aria-label="Camera view">
            <option value="chase">Chase view</option>
            <option value="driver">Operator view</option>
            <option value="overhead">Overhead view</option>
          </select>
          <details className="rr-session-menu">
            <summary aria-label="Simulator menu">Menu</summary>
            <div className="rr-session-menu-popover">
              <button type="button" onClick={onChangeEquipment}>Change equipment</button>
              {gyroAvailable && <button type="button" aria-pressed={gyroEnabled} onClick={onToggleGyro}>Gyro {gyroEnabled ? "on" : "off"}</button>}
            </div>
          </details>
        </div>
      </div>
      <p>{message}</p>
      <div className="rr-hud-actions">
        {!inspectionMode && [0, 3, 4].includes(stage) && <button className="rr-primary" onClick={advance}>{stage === 0 ? "Ready" : stage === 3 ? "Clearance" : "Brake released"}</button>}
        {!inspectionMode && stage === 1 && <button className={hud.ready ? "rr-primary" : "rr-primary rr-disabled"} disabled={!hud.ready} onClick={capture}>{hud.ready ? "Capture nose gear" : `Align ${hud.capture.toFixed(1)} m`}</button>}
        {!inspectionMode && stage === 6 && <button className="rr-primary" onClick={lower}>Lower cradle</button>}
        <button className="rr-secondary" onClick={reset}>Reset</button>
      </div>
    </section>
    <aside className="rr-metrics">
      <span>Tug <b>{hud.tug}</b></span>
      <span>Speed <b>{(hud.speed * 2.237).toFixed(1)} mph</b></span>
      <span>Stop <b>{Math.max(0, hud.stop).toFixed(1)} m</b></span>
      <span>Articulation <b>{hud.articulation.toFixed(1)}°</b></span>
      <span>Connection <b>{hud.phase}</b></span>
      <span>Aircraft <b>{hud.aircraft}</b></span>
      {[CONNECTION_PHASES.CAPTURING, CONNECTION_PHASES.LOWERING].includes(hud.phase) && <span>Cycle <b>{Math.round(hud.progress * 100)}%</b></span>}
    </aside>
    <aside className="rr-score-float">{inspectionMode ? <>Inspection <b>FREE</b><span>Airport drive</span></> : <>Score <b>{hud.score}</b><span>{hud.warning ? "JACKKNIFE" : "Stable"}</span></>}</aside>
    <div className="rr-steer">
      <button
        type="button"
        aria-label="Steer left"
        onPointerDown={() => { driveRef.current.steer = 1; }}
        onPointerUp={releaseSteer}
        onPointerCancel={releaseSteer}
        onPointerLeave={releaseSteer}
      >◀</button>
      <button
        type="button"
        onPointerDown={() => { driveRef.current.brake = true; }}
        onPointerUp={releaseBrake}
        onPointerCancel={releaseBrake}
        onPointerLeave={releaseBrake}
      >Brake</button>
      <button
        type="button"
        aria-label="Steer right"
        onPointerDown={() => { driveRef.current.steer = -1; }}
        onPointerUp={releaseSteer}
        onPointerCancel={releaseSteer}
        onPointerLeave={releaseSteer}
      >▶</button>
    </div>
    <div className="rr-throttle">
      <button className="rr-direction" type="button" onClick={() => {
        const next = driveRef.current.direction === 1 ? -1 : 1;
        driveRef.current.direction = next;
        setDirection(next === 1 ? "FWD" : "REV");
      }}>{direction}</button>
      <input
        className="rr-power-slider"
        aria-label="Power"
        type="range"
        min="0"
        max="100"
        step="1"
        value={throttle}
        onInput={(event) => setPower(event.currentTarget.value)}
        onChange={(event) => setPower(event.currentTarget.value)}
      />
      <button className="rr-idle" type="button" onClick={() => setPower(0)}>Idle</button>
      <div className="rr-throttle-label">Power {throttle}%</div>
    </div>
  </div>;
}
