export const KPHX_T4_EXACT_GSE_AUTHORITY = Object.freeze({
  authority: "KPHX-1.75.1-WED-T4-authored-static-GSE-exact-materialized-v1",
  sourceWedSha256: "59d9676dbccdaed24f2308e0597aacf846c8244cbadaefd8558af1e5c0dda498",
  expectedPlacementCount: 884,
  expectedUniqueResourceCount: 33,
  misterX: Object.freeze({
    manifestUrl: "/models/kphx-full-airport/batches/t4-misterx.manifest.json",
    expectedPlacementCount: 861,
    expectedUniqueResourceCount: 32,
    resources: Object.freeze([
    "MisterX_Library/Airport/Vehicles/Baggage_Carts/American.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Carts/American_Eagle.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Carts/American_Eagle_Open.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Carts/American_Open.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Carts/Southwest_Old_Open.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Carts/Southwest_Open.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Tractors/American.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Tractors/Southwest.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Trains/Cart2_Southwest.obj",
    "MisterX_Library/Airport/Vehicles/Baggage_Trains/Cart2_Southwest_Full.obj",
    "MisterX_Library/Airport/Vehicles/Belt_Loaders/Active/American.obj",
    "MisterX_Library/Airport/Vehicles/Belt_Loaders/American.obj",
    "MisterX_Library/Airport/Vehicles/Belt_Loaders/Southwest.obj",
    "MisterX_Library/Airport/Vehicles/Cargo_Dollies/Cargo_Dolly_Large.obj",
    "MisterX_Library/Airport/Vehicles/Cargo_Dollies/ULD_American_Dolly.obj",
    "MisterX_Library/Airport/Vehicles/Catering_Trucks/Medium/LSG.obj",
    "MisterX_Library/Airport/Vehicles/De_Icing_Trucks/Generic.obj",
    "MisterX_Library/Airport/Vehicles/Fuel_Trucks/Large/ASIG.obj",
    "MisterX_Library/Airport/Vehicles/Fuel_Trucks/Medium/ASIG.obj",
    "MisterX_Library/Airport/Vehicles/GPUs/Large/Generic_Stowed.obj",
    "MisterX_Library/Airport/Vehicles/GPUs/Medium/Generic_Stowed.obj",
    "MisterX_Library/Airport/Vehicles/Pushback_Trucks/Medium/Generic.obj",
    "MisterX_Library/Airport/Vehicles/Pushback_Trucks/Medium/Southwest.obj",
    "MisterX_Library/Airport/Vehicles/Trucks/Active/Pickup_Blue.obj",
    "MisterX_Library/Airport/Vehicles/Trucks/Active/Pickup_White.obj",
    "MisterX_Library/Airport/Vehicles/Trucks/Active/Van_White.obj",
    "MisterX_Library/Airport/Vehicles/Trucks/Pickup_White.obj",
    "MisterX_Library/Airport/Vehicles/Trucks/Van_White.obj",
    "MisterX_Library/Airport/Vehicles/Trucks/Van_White_2.obj",
    "MisterX_Library/Airport/Vehicles/ULD_Loaders/Generic.obj",
    "MisterX_Library/Vehicles/Trucks/Van_White.obj",
    "MisterX_Library/Vehicles/Trucks/Van_White_2.obj"
]),
  }),
  cdb: Object.freeze({
    manifestUrl: "/models/kphx-full-airport/batches/t4-cdb.manifest.json",
    expectedPlacementCount: 23,
    expectedUniqueResourceCount: 1,
    resources: Object.freeze([
    "CDB-Library/Airport/GSE/others/objects_airConditionerBig.obj"
]),
  }),
  exclusions: Object.freeze({
    staticAircraft: true,
    people: true,
    rampObjects: true,
    construction: true,
    unresolvedLaminarLibrary: true,
    unresolvedOpenSceneryX: true,
  }),
});
