export const KPHX_TERMINAL_CHUNK = Object.freeze({
  id: "kphx-terminals-v1751",
  sourceFolder: "Terminals",
  runtimeBaseUrl: "/models/kphx-full-airport/terminals",
  placements: Object.freeze([
    Object.freeze({
      wedObjectId: "7424",
      name: "Terminal3a",
      sourceResource: "Terminals/Terminal3a.obj",
      assetUrl: "/models/kphx-full-airport/terminals/Terminal3a/Terminal3a.gltf",
      latitude: 33.436168819,
      longitude: -112.008763064,
      headingDegrees: 0,
      customMsl: false,
      mslMeters: 0,
    }),
    Object.freeze({
      wedObjectId: "11792",
      name: "Terminal3Garage",
      sourceResource: "Terminals/Terminal3Garage.obj",
      assetUrl: "/models/kphx-full-airport/terminals/Terminal3Garage/Terminal3Garage.gltf",
      latitude: 33.435447284,
      longitude: -112.008758475,
      headingDegrees: 0,
      customMsl: false,
      mslMeters: 0,
    }),
    Object.freeze({
      wedObjectId: "2327",
      name: "Terminal4",
      sourceResource: "Terminals/Terminal4.obj",
      assetUrl: "/models/kphx-full-airport/terminals/Terminal4/Terminal4.gltf",
      latitude: 33.434761986,
      longitude: -111.996702473,
      headingDegrees: 0,
      customMsl: false,
      mslMeters: 0,
    }),
    Object.freeze({
      wedObjectId: "5301",
      name: "Terminal4b",
      sourceResource: "Terminals/Terminal4b.obj",
      assetUrl: "/models/kphx-full-airport/terminals/Terminal4b/Terminal4b.gltf",
      latitude: 33.436209533,
      longitude: -111.996664410,
      headingDegrees: 0,
      customMsl: false,
      mslMeters: 0,
    }),
  ]),
  unusedSourceAssets: Object.freeze([
    "Terminals/Terminal3b.obj",
    "Terminals/Terminal2.obj",
    "Terminals/Terminal2Building.obj",
    "Terminals/BuildingT2.obj",
    "Terminals/T2Stands.obj",
  ]),
  policy: "Only WED-placed terminal resources are instantiated. Unplaced source assets are retained as source evidence but receive no invented placement.",
});
